"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ActionMenu } from "@/components/ui/action-menu";
import { Button } from "@/components/ui/button";
import { CustomSelect } from "@/components/ui/custom-select";
import { Pagination } from "@/components/ui/pagination";
import { SearchInput } from "@/components/ui/search-input";
import { useConfirmDialog, useToast } from "@/components/ui/feedback-provider";
import { cn } from "@/lib/utils";
import { getMockProviderServices, providerServiceCategories, providerServiceStatuses } from "@/mocks/provider/provider-services.mock";
import type { ProviderServiceMock, ProviderServiceStatus } from "@/types/service";

const statusStyle: Record<ProviderServiceStatus, string> = { draft: "bg-slate-100 text-slate-700", pending_review: "bg-amber-100 text-amber-800", active: "bg-emerald-100 text-emerald-800", rejected: "bg-red-100 text-red-800", hidden: "bg-blue-100 text-blue-800", suspended: "bg-purple-100 text-purple-800" };
const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" });

export function ServiceStatusBadge({ status }: { status: ProviderServiceStatus }) { return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-xs font-extrabold capitalize", statusStyle[status])}>{status.replaceAll("_", " ")}</span>; }
export function RejectionReasonAlert({ reason }: { reason?: string }) { if (!reason) return null; return <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-semibold leading-5 text-red-800"><strong>Rejection reason:</strong> {reason}</div>; }

type ActionProps = { service: ProviderServiceMock; onAction: (action: "duplicate" | "hide" | "show" | "archive", service: ProviderServiceMock) => void };
export function ServiceActionMenu({ service, onAction }: ActionProps) {
  const items = [{ label: "Edit service", onClick: () => location.assign(`/provider/services/${service.id}/edit`) }, { label: "Duplicate service", onClick: () => onAction("duplicate", service) }];
  if (service.status === "active") items.push({ label: "Hide service", onClick: () => onAction("hide", service) });
  if (service.status === "hidden") items.push({ label: "Show service", onClick: () => onAction("show", service) });
  if (service.status !== "suspended") items.push({ label: service.futureBookingCount ? "Archive (future bookings retained)" : "Archive service", onClick: () => onAction("archive", service) });
  return <ActionMenu items={items} />;
}

export function ServiceTable({ services, onAction }: { services: ProviderServiceMock[]; onAction: ActionProps["onAction"] }) {
  return <div className="overflow-x-auto rounded-3xl border border-border-subtle bg-surface shadow-sm"><table className="min-w-[1050px] w-full text-left"><thead className="bg-surface-muted text-xs font-extrabold uppercase tracking-wide text-subtle"><tr>{["Service", "Category", "Price", "Duration", "Bookings", "Rating", "Status", "Updated", ""].map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody className="divide-y divide-border-subtle">{services.map((service) => <tr key={service.id} className="align-top hover:bg-surface-muted/50"><td className="max-w-64 px-4 py-4"><Link href={`/provider/services/${service.id}/edit`} className="font-extrabold text-foreground hover:text-brand">{service.name}</Link>{service.status === "rejected" && <div className="mt-2"><RejectionReasonAlert reason={service.rejectionReason} /></div>}</td><td className="px-4 py-4 text-sm text-muted">{service.category}</td><td className="px-4 py-4 text-sm font-bold text-foreground">{money.format(service.basePrice)}</td><td className="px-4 py-4 text-sm text-muted">{service.duration} min</td><td className="px-4 py-4 text-sm text-muted">{service.bookingCount}</td><td className="px-4 py-4 text-sm font-bold text-foreground">★ {service.rating}</td><td className="px-4 py-4"><ServiceStatusBadge status={service.status} /></td><td className="px-4 py-4 text-xs text-muted">{new Date(service.updatedAt).toLocaleDateString("en-GB")}</td><td className="px-4 py-4"><ServiceActionMenu service={service} onAction={onAction} /></td></tr>)}</tbody></table></div>;
}

export function ServiceCard({ service, onAction }: { service: ProviderServiceMock; onAction: ActionProps["onAction"] }) {
  return <article className="overflow-hidden rounded-3xl border border-border-subtle bg-surface shadow-sm"><div className="h-36 bg-brand-soft bg-cover bg-center" style={service.images[0] ? { backgroundImage: `url(${service.images[0].url})` } : undefined} /><div className="p-4"><div className="flex items-start justify-between gap-3"><div><ServiceStatusBadge status={service.status} /><Link href={`/provider/services/${service.id}/edit`} className="mt-2 block text-lg font-extrabold text-foreground hover:text-brand">{service.name}</Link><p className="mt-1 text-sm text-muted">{service.category} · {service.duration} min</p></div><ServiceActionMenu service={service} onAction={onAction} /></div><div className="mt-4 flex items-center justify-between"><strong className="text-foreground">{money.format(service.basePrice)}</strong><span className="text-sm font-bold text-muted">★ {service.rating} · {service.bookingCount} bookings</span></div>{service.status === "rejected" && <div className="mt-3"><RejectionReasonAlert reason={service.rejectionReason} /></div>}</div></article>;
}

export function ServiceFilters({ search, category, status, sort, view, onChange }: { search: string; category: string; status: string; sort: string; view: "table" | "grid"; onChange: (key: string, value: string) => void }) {
  return <div className="grid gap-3 rounded-3xl border border-border-subtle bg-surface p-4 shadow-sm md:grid-cols-2 xl:grid-cols-[1fr_180px_180px_190px_auto]"><SearchInput value={search} onChange={(value) => onChange("search", value)} placeholder="Search services..." /><CustomSelect value={category} options={[{ label: "All categories", value: "all" }, ...providerServiceCategories.map((item) => ({ label: item, value: item }))]} onValueChange={(value) => onChange("category", value)} /><CustomSelect value={status} options={[{ label: "All statuses", value: "all" }, ...providerServiceStatuses.map((item) => ({ label: item.replaceAll("_", " "), value: item }))]} onValueChange={(value) => onChange("status", value)} /><CustomSelect value={sort} options={[{ label: "Recently updated", value: "updated" }, { label: "Name A–Z", value: "name" }, { label: "Price low–high", value: "price" }, { label: "Most booked", value: "bookings" }]} onValueChange={(value) => onChange("sort", value)} /><div className="flex rounded-xl border border-border-muted p-1"><button className={cn("flex-1 rounded-lg px-3 text-sm font-bold", view === "table" && "bg-brand text-white")} onClick={() => onChange("view", "table")}>Table</button><button className={cn("flex-1 rounded-lg px-3 text-sm font-bold", view === "grid" && "bg-brand text-white")} onClick={() => onChange("view", "grid")}>Grid</button></div></div>;
}

export function ProviderServiceListMock() {
  const [services, setServices] = useState<ProviderServiceMock[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState(""); const [category, setCategory] = useState("all"); const [status, setStatus] = useState("all"); const [sort, setSort] = useState("updated"); const [view, setView] = useState<"table" | "grid">("table"); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(5);
  const confirm = useConfirmDialog(); const { showToast } = useToast();
  useEffect(() => { let active = true; getMockProviderServices().then((data) => { if (active) setServices(data); }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "Unable to load services."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const filtered = useMemo(() => { const result = services.filter((item) => item.name.toLowerCase().includes(search.toLowerCase()) && (category === "all" || item.category === category) && (status === "all" || item.status === status)); return result.sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "price" ? a.basePrice - b.basePrice : sort === "bookings" ? b.bookingCount - a.bookingCount : b.updatedAt.localeCompare(a.updatedAt)); }, [services, search, category, status, sort]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((Math.min(page, totalPages) - 1) * pageSize, Math.min(page, totalPages) * pageSize);
  function change(key: string, value: string) { setPage(1); if (key === "search") setSearch(value); if (key === "category") setCategory(value); if (key === "status") setStatus(value); if (key === "sort") setSort(value); if (key === "view") setView(value as "table" | "grid"); }
  async function action(type: "duplicate" | "hide" | "show" | "archive", service: ProviderServiceMock) { const result = await confirm({ title: `${type[0].toUpperCase() + type.slice(1)} ${service.name}?`, description: type === "archive" && service.futureBookingCount ? `${service.futureBookingCount} future booking(s) will remain available; permanent deletion is not offered.` : "This action only updates the current mock session.", confirmLabel: type[0].toUpperCase() + type.slice(1), tone: type === "archive" ? "danger" : "default" }); if (!result.confirmed) return; if (type === "duplicate") setServices((items) => [{ ...service, id: `copy-${crypto.randomUUID()}`, name: `${service.name} (Copy)`, status: "draft", bookingCount: 0, futureBookingCount: 0, updatedAt: new Date().toISOString() }, ...items]); else setServices((items) => items.map((item) => item.id === service.id ? { ...item, status: type === "hide" ? "hidden" : type === "show" ? "active" : "hidden", visibility: type === "show" ? "public" : "private", updatedAt: new Date().toISOString() } : item)); showToast(`Service ${type} action completed in mock mode.`, "success"); }
  if (loading) return <div className="space-y-4 animate-pulse"><div className="h-28 rounded-3xl bg-surface-muted" /><div className="h-16 rounded-3xl bg-surface-muted" />{Array.from({ length: 5 }).map((_, index) => <div key={index} className="h-20 rounded-2xl bg-surface-muted" />)}</div>;
  if (error) return <div className="rounded-3xl border border-red-200 bg-red-50 p-8 text-center"><h2 className="text-xl font-extrabold text-red-950">Services unavailable</h2><p className="mt-2 text-sm text-red-800">{error}</p><Button className="mt-4" onClick={() => location.reload()}>Try again</Button></div>;
  return <div className="space-y-5"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-black text-foreground">Services</h1><p className="mt-1 text-sm text-muted">Manage your PetLink service catalog in frontend mock mode.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => { setError("Simulated service list error."); }}>Simulate error</Button><Link href="/provider/services/create" className="inline-flex h-11 items-center rounded-xl bg-brand px-5 text-sm font-bold text-white">Add Service</Link></div></header><ServiceFilters search={search} category={category} status={status} sort={sort} view={view} onChange={change} />{visible.length === 0 ? <div className="rounded-3xl border border-dashed border-border-muted bg-surface px-6 py-16 text-center"><div className="text-4xl">✦</div><h2 className="mt-3 text-lg font-extrabold text-foreground">No services found</h2><p className="mt-1 text-sm text-muted">Adjust the filters or create a new service.</p></div> : view === "table" ? <ServiceTable services={visible} onAction={action} /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((service) => <ServiceCard key={service.id} service={service} onAction={action} />)}</div>}<Pagination page={Math.min(page, totalPages)} totalPages={totalPages} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(1); }} /></div>;
}
