"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { CustomSelect } from "@/components/ui/custom-select";
import { Pagination } from "@/components/ui/pagination";
import { SearchInput } from "@/components/ui/search-input";
import { cn } from "@/lib/utils";
import { getMockProviderDisputes } from "@/mocks/provider/provider-disputes.mock";
import type { ProviderDisputeMock, ProviderDisputeStatus } from "@/types/provider-dispute";

export const disputeStatuses: ProviderDisputeStatus[] = ["open", "awaiting_provider", "awaiting_customer", "under_review", "resolved_customer", "resolved_provider", "closed"];
const tones: Record<ProviderDisputeStatus, string> = { open: "bg-red-100 text-red-800", awaiting_provider: "bg-amber-100 text-amber-800", awaiting_customer: "bg-blue-100 text-blue-800", under_review: "bg-purple-100 text-purple-800", resolved_customer: "bg-orange-100 text-orange-800", resolved_provider: "bg-emerald-100 text-emerald-800", closed: "bg-slate-200 text-slate-700" };
const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 });
export function DisputeStatusBadge({ status }: { status: ProviderDisputeStatus }) { return <span className={cn("rounded-full px-2.5 py-1 text-xs font-extrabold capitalize", tones[status])}>{status.replaceAll("_", " ")}</span>; }

export function ProviderDisputeListMock() {
  const [items, setItems] = useState<ProviderDisputeMock[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(5);
  useEffect(() => { let active = true; getMockProviderDisputes().then((data) => { if (active) setItems(data); }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "Unable to load disputes."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const filtered = useMemo(() => items.filter((item) => `${item.code} ${item.booking.code} ${item.customer.name} ${item.reason}`.toLowerCase().includes(search.toLowerCase()) && (status === "all" || item.status === status)), [items, search, status]); const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  if (loading) return <div className="space-y-4 animate-pulse"><div className="h-28 rounded-3xl bg-surface-muted" />{Array.from({ length: 6 }).map((_, i) => <div key={i} className="h-20 rounded-2xl bg-surface-muted" />)}</div>;
  if (error) return <div className="rounded-3xl border border-red-200 bg-red-50 p-8 text-center"><h1 className="text-xl font-extrabold text-red-950">Disputes unavailable</h1><p className="mt-2 text-sm text-red-800">{error}</p><Button className="mt-4" onClick={() => location.reload()}>Try again</Button></div>;
  return <div className="space-y-5"><header className="flex flex-col justify-between gap-4 rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-black">Disputes</h1><p className="mt-2 text-sm text-muted">Review customer claims, deadlines, evidence, and local mock responses.</p></div><Button variant="outline" onClick={() => setError("Simulated dispute loading error.")}>Simulate error</Button></header><section className="grid gap-3 rounded-3xl border border-border-subtle bg-surface p-4 shadow-sm md:grid-cols-[1fr_220px]"><SearchInput value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Code, booking, customer or reason..." /><CustomSelect value={status} options={[{ label: "All statuses", value: "all" }, ...disputeStatuses.map((item) => ({ label: item.replaceAll("_", " "), value: item }))]} onValueChange={(value) => { setStatus(value); setPage(1); }} /></section>{visible.length ? <><div className="overflow-x-auto rounded-3xl border border-border-subtle bg-surface shadow-sm"><table className="min-w-[1200px] w-full text-left"><thead className="bg-surface-muted text-xs font-extrabold uppercase tracking-wide text-subtle"><tr>{["Dispute", "Booking", "Customer", "Reason", "Amount", "Created", "Deadline", "Status", ""].map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody className="divide-y divide-border-subtle">{visible.map((item) => <tr key={item.id} className="hover:bg-surface-muted/50"><td className="px-4 py-4"><Link href={`/provider/disputes/${item.id}`} className="font-extrabold text-brand">{item.code}</Link></td><td className="px-4 py-4 text-sm font-bold">{item.booking.code}</td><td className="px-4 py-4 text-sm">{item.customer.name}</td><td className="max-w-64 px-4 py-4 text-sm text-muted">{item.reason}</td><td className="px-4 py-4 font-black">{money.format(item.disputedAmount)}</td><td className="px-4 py-4 text-xs text-muted">{formatDate(item.createdAt)}</td><td className="px-4 py-4 text-xs font-bold text-orange-700">{formatDate(item.responseDeadline)}</td><td className="px-4 py-4"><DisputeStatusBadge status={item.status} /></td><td className="px-4 py-4"><Link href={`/provider/disputes/${item.id}`} className="text-sm font-extrabold text-brand">View →</Link></td></tr>)}</tbody></table></div><Pagination page={page} totalPages={totalPages} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={(value) => { setPageSize(value); setPage(1); }} /></> : <div className="rounded-3xl border border-dashed border-border-muted bg-surface py-16 text-center"><h2 className="text-lg font-extrabold">No disputes found</h2><p className="mt-1 text-sm text-muted">Adjust the search or status filter.</p></div>}</div>;
}
function formatDate(value: string) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
