"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ActionMenu } from "@/components/ui/action-menu";
import { Button } from "@/components/ui/button";
import { CustomSelect } from "@/components/ui/custom-select";
import { Input } from "@/components/ui/input";
import { Pagination } from "@/components/ui/pagination";
import { SearchInput } from "@/components/ui/search-input";
import { useConfirmDialog, useToast } from "@/components/ui/feedback-provider";
import { cn } from "@/lib/utils";
import { getMockProviderBookings } from "@/mocks/provider/provider-bookings.mock";
import type { ProviderBookingMock, ProviderBookingStatus, ProviderPaymentStatus } from "@/types/provider-booking";

const bookingStatuses: ProviderBookingStatus[] = ["pending", "confirmed", "checked_in", "checked_out", "completed", "cancelled", "rejected", "dispute", "no_arrival"];
const bookingTone: Record<ProviderBookingStatus, string> = { pending: "bg-amber-100 text-amber-800", confirmed: "bg-blue-100 text-blue-800", checked_in: "bg-cyan-100 text-cyan-800", checked_out: "bg-indigo-100 text-indigo-800", completed: "bg-emerald-100 text-emerald-800", cancelled: "bg-slate-200 text-slate-700", rejected: "bg-red-100 text-red-800", dispute: "bg-orange-100 text-orange-800", no_arrival: "bg-purple-100 text-purple-800" };
const paymentTone: Record<ProviderPaymentStatus, string> = { pending: "bg-amber-100 text-amber-800", paid: "bg-emerald-100 text-emerald-800", failed: "bg-red-100 text-red-800", refunded: "bg-slate-200 text-slate-700", cash_pending: "bg-blue-100 text-blue-800" };
const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" });

export function BookingStatusBadge({ status }: { status: ProviderBookingStatus }) { return <span className={cn("rounded-full px-2.5 py-1 text-xs font-extrabold capitalize", bookingTone[status])}>{status.replaceAll("_", " ")}</span>; }
export function PaymentStatusBadge({ status }: { status: ProviderPaymentStatus }) { return <span className={cn("rounded-full px-2.5 py-1 text-xs font-extrabold capitalize", paymentTone[status])}>{status.replaceAll("_", " ")}</span>; }

type BookingAction = "accept" | "reject" | "check_in" | "reschedule" | "no_arrival" | "check_out" | "issue";
export function BookingActions({ booking, onAction }: { booking: ProviderBookingMock; onAction: (action: BookingAction, booking: ProviderBookingMock) => void }) {
  const actions = booking.status === "pending" ? [{ label: "Accept", action: "accept" }, { label: "Reject", action: "reject" }] : booking.status === "confirmed" ? [{ label: "Check in", action: "check_in" }, { label: "Propose reschedule", action: "reschedule" }, { label: "Report no arrival", action: "no_arrival" }] : booking.status === "checked_in" ? [{ label: "Check out", action: "check_out" }, { label: "Report issue", action: "issue" }] : [];
  return <ActionMenu items={[{ label: "View details", onClick: () => location.assign(`/provider/bookings/${booking.id}`) }, ...actions.map((item) => ({ label: item.label, onClick: () => onAction(item.action as BookingAction, booking) })), ...(booking.status === "checked_out" ? [{ label: "View dispute countdown", onClick: () => location.assign(`/provider/bookings/${booking.id}`) }] : []), ...(booking.status === "dispute" ? [{ label: "View dispute", onClick: () => location.assign(`/provider/bookings/${booking.id}`) }] : []), ...(booking.status === "completed" ? [{ label: "View settlement", onClick: () => location.assign(`/provider/bookings/${booking.id}`) }] : [])]} />;
}

export function BookingTable({ bookings, onAction }: { bookings: ProviderBookingMock[]; onAction: (action: BookingAction, booking: ProviderBookingMock) => void }) {
  return <div className="overflow-x-auto rounded-3xl border border-border-subtle bg-surface shadow-sm"><table className="min-w-[1250px] w-full text-left"><thead className="bg-surface-muted text-xs font-extrabold uppercase tracking-wide text-subtle"><tr>{["Booking", "Customer / Pet", "Service", "Appointment", "Payment", "Status", "Total", ""].map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody className="divide-y divide-border-subtle">{bookings.map((booking) => <tr key={booking.id} className="hover:bg-surface-muted/50"><td className="px-4 py-4"><Link href={`/provider/bookings/${booking.id}`} className="font-extrabold text-brand">{booking.code}</Link></td><td className="px-4 py-4"><p className="text-sm font-bold text-foreground">{booking.customer.name}</p><p className="text-xs text-muted">{booking.pet.name} · {booking.pet.breed}</p></td><td className="max-w-56 px-4 py-4 text-sm font-semibold text-foreground">{booking.service.name}</td><td className="px-4 py-4 text-sm text-muted">{formatDateTime(booking.appointmentAt)}</td><td className="px-4 py-4"><p className="mb-2 text-xs font-bold capitalize text-muted">{booking.paymentMethod.replaceAll("_", " ")}</p><PaymentStatusBadge status={booking.paymentStatus} /></td><td className="px-4 py-4"><BookingStatusBadge status={booking.status} /></td><td className="px-4 py-4 text-sm font-extrabold">{money.format(booking.totalAmount)}</td><td className="px-4 py-4"><BookingActions booking={booking} onAction={onAction} /></td></tr>)}</tbody></table></div>;
}

export function BookingCalendarView({ bookings }: { bookings: ProviderBookingMock[] }) { const days = Array.from({ length: 31 }, (_, i) => i + 1); return <div className="rounded-3xl border border-border-subtle bg-surface p-4 shadow-sm"><div className="grid grid-cols-7 gap-2">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <div key={day} className="py-2 text-center text-xs font-extrabold text-subtle">{day}</div>)}<div /><div />{days.map((day) => { const items = bookings.filter((item) => new Date(item.appointmentAt).getDate() === day); return <div key={day} className="min-h-28 rounded-2xl border border-border-subtle p-2"><strong className="text-xs">{day}</strong><div className="mt-2 space-y-1">{items.slice(0, 3).map((item) => <Link key={item.id} href={`/provider/bookings/${item.id}`} className={cn("block truncate rounded-lg px-1.5 py-1 text-[10px] font-bold", bookingTone[item.status])}>{new Date(item.appointmentAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })} {item.pet.name}</Link>)}{items.length > 3 && <p className="text-[10px] font-bold text-subtle">+{items.length - 3} more</p>}</div></div>; })}</div></div>; }

export function ProviderBookingListMock() {
  const [bookings, setBookings] = useState<ProviderBookingMock[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [method, setMethod] = useState("all"); const [service, setService] = useState("all"); const [date, setDate] = useState(""); const [view, setView] = useState<"table" | "calendar">("table"); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(5); const confirm = useConfirmDialog(); const { showToast } = useToast();
  useEffect(() => { let active = true; getMockProviderBookings().then((data) => { if (active) setBookings(data); }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "Unable to load bookings."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const serviceOptions = useMemo(() => Array.from(new Set(bookings.map((item) => item.service.name))), [bookings]);
  const filtered = useMemo(() => bookings.filter((item) => `${item.code} ${item.customer.name} ${item.pet.name}`.toLowerCase().includes(search.toLowerCase()) && (status === "all" || item.status === status) && (method === "all" || item.paymentMethod === method) && (service === "all" || item.service.name === service) && (!date || item.appointmentAt.slice(0, 10) === date)), [bookings, search, status, method, service, date]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((Math.min(page, totalPages) - 1) * pageSize, Math.min(page, totalPages) * pageSize);
  async function action(type: BookingAction, booking: ProviderBookingMock) { const result = await confirm({ title: `${labelAction(type)} ${booking.code}?`, description: "This action only updates the current mock state and timeline.", confirmLabel: labelAction(type), tone: type === "reject" || type === "no_arrival" ? "danger" : "default" }); if (!result.confirmed) return; const nextStatus: Partial<Record<BookingAction, ProviderBookingStatus>> = { accept: "confirmed", reject: "rejected", check_in: "checked_in", no_arrival: "no_arrival", check_out: "checked_out", issue: "dispute" }; setBookings((items) => items.map((item) => item.id === booking.id ? { ...item, status: nextStatus[type] ?? item.status, appointmentAt: type === "reschedule" ? new Date(new Date(item.appointmentAt).getTime() + 86400000).toISOString() : item.appointmentAt, timeline: [...item.timeline, { id: crypto.randomUUID(), title: labelAction(type), description: `${labelAction(type)} action recorded in mock mode.`, occurredAt: new Date().toISOString(), actor: "Provider" }] } : item)); showToast(`${labelAction(type)} completed in mock mode.`, "success"); }
  function resetPage(setter: (value: string) => void, value: string) { setter(value); setPage(1); }
  if (loading) return <div className="space-y-4 animate-pulse"><div className="h-28 rounded-3xl bg-surface-muted" /><div className="h-24 rounded-3xl bg-surface-muted" />{Array.from({ length: 5 }).map((_, i) => <div key={i} className="h-20 rounded-2xl bg-surface-muted" />)}</div>;
  if (error) return <div className="rounded-3xl border border-red-200 bg-red-50 p-8 text-center"><h2 className="text-xl font-extrabold text-red-950">Bookings unavailable</h2><p className="mt-2 text-sm text-red-800">{error}</p><Button className="mt-4" onClick={() => location.reload()}>Try again</Button></div>;
  return <div className="space-y-5"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-black">Bookings</h1><p className="mt-1 text-sm text-muted">Manage provider appointments through a local mock lifecycle.</p></div><Button variant="outline" onClick={() => setError("Simulated booking list error.")}>Simulate error</Button></header><div className="grid gap-3 rounded-3xl border border-border-subtle bg-surface p-4 shadow-sm md:grid-cols-2 xl:grid-cols-[1fr_160px_170px_220px_170px_auto]"><SearchInput value={search} onChange={(value) => resetPage(setSearch, value)} placeholder="Code, customer or pet..." /><CustomSelect value={status} options={[{ label: "All statuses", value: "all" }, ...bookingStatuses.map((item) => ({ label: item.replaceAll("_", " "), value: item }))]} onValueChange={(value) => resetPage(setStatus, value)} /><CustomSelect value={method} options={[{ label: "All payments", value: "all" }, ...["card", "bank_transfer", "cash", "wallet"].map((item) => ({ label: item.replaceAll("_", " "), value: item }))]} onValueChange={(value) => resetPage(setMethod, value)} /><CustomSelect value={service} options={[{ label: "All services", value: "all" }, ...serviceOptions.map((item) => ({ label: item, value: item }))]} onValueChange={(value) => resetPage(setService, value)} /><Input aria-label="Filter booking date" type="date" value={date} onChange={(e) => resetPage(setDate, e.target.value)} /><div className="flex rounded-xl border border-border-muted p-1"><button className={cn("flex-1 rounded-lg px-3 text-sm font-bold", view === "table" && "bg-brand text-white")} onClick={() => setView("table")}>Table</button><button className={cn("flex-1 rounded-lg px-3 text-sm font-bold", view === "calendar" && "bg-brand text-white")} onClick={() => setView("calendar")}>Calendar</button></div></div>{filtered.length === 0 ? <div className="rounded-3xl border border-dashed border-border-muted bg-surface py-16 text-center"><h2 className="text-lg font-extrabold">No bookings found</h2><p className="mt-1 text-sm text-muted">Adjust the current search or filters.</p></div> : view === "table" ? <><BookingTable bookings={visible} onAction={action} /><Pagination page={Math.min(page, totalPages)} totalPages={totalPages} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={(value) => { setPageSize(value); setPage(1); }} /></> : <BookingCalendarView bookings={filtered} />}</div>;
}

function formatDateTime(value: string) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function labelAction(value: BookingAction) { return ({ accept: "Accept booking", reject: "Reject booking", check_in: "Check in", reschedule: "Propose reschedule", no_arrival: "Report no arrival", check_out: "Check out", issue: "Report issue" })[value]; }
