"use client";

import Link from "next/link";
import { useState } from "react";
import { AxiosError } from "axios";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/components/ui/feedback-provider";
import { useCreateWithdrawalApi, useNotificationActionsApi, useProviderAvailabilityApi, useProviderBookingActionApi, useProviderBookingsApi, useProviderNotificationsApi, useProviderProfileApi, useProviderServicesApi, useProviderTransactionsApi, useProviderWalletApi, useProviderWithdrawalsApi, useSaveProviderServiceApi, useSaveWorkingHoursApi, useToggleProviderServiceApi, useUpdateProviderProfileApi } from "@/apis/provider/live-queries";
import { useMyProviderDocuments, useMyProviderInfo, useUploadProviderDocument } from "@/apis/provider/verification/queries";
import type { WorkingHourApi } from "@/types/provider-api";

const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" });
const date = (value?: string | null) => value ? new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const errorText = (error: unknown) => error instanceof AxiosError ? String(error.response?.data?.message ?? error.message) : "Không thể tải dữ liệu. Vui lòng thử lại.";

function Header({ title, description }: { title: string; description: string }) { return <header className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6"><h1 className="text-3xl font-black">{title}</h1><p className="mt-2 text-sm text-muted">{description}</p></header>; }
function Loading() { return <div className="grid gap-3" aria-label="Đang tải"><div className="h-24 animate-pulse rounded-3xl bg-surface-muted"/><div className="h-52 animate-pulse rounded-3xl bg-surface-muted"/></div>; }
function ErrorState({ error, retry }: { error: unknown; retry: () => void }) { return <div className="rounded-3xl border border-red-200 bg-red-50 p-8 text-center"><h2 className="font-extrabold text-red-900">Không tải được dữ liệu</h2><p className="mt-2 text-sm text-red-700">{errorText(error)}</p><Button className="mt-4" onClick={retry}>Thử lại</Button></div>; }
function Badge({ value }: { value: string }) { return <span className="inline-flex rounded-full bg-brand-soft px-2.5 py-1 text-xs font-extrabold text-brand">{value.replaceAll("_", " ")}</span>; }

export function ProviderServicesLive() {
  const query = useProviderServicesApi(); const toggle = useToggleProviderServiceApi(); const { showToast } = useToast();
  if (query.isLoading) return <Loading/>; if (query.isError) return <ErrorState error={query.error} retry={() => void query.refetch()}/>;
  const items = query.data?.items ?? [];
  return <div className="space-y-5"><Header title="Dịch vụ" description="Dữ liệu được tải từ API dịch vụ Provider hiện có."/><div className="flex justify-end"><Link className="rounded-xl bg-brand px-5 py-3 text-sm font-bold text-white" href="/provider/services/create">Tạo dịch vụ</Link></div>{items.length === 0 ? <Empty text="Chưa có dịch vụ."/> : <div className="overflow-x-auto rounded-3xl border bg-surface"><table className="min-w-[760px] w-full text-left"><thead className="bg-surface-muted text-xs uppercase"><tr>{["Dịch vụ","Giá","Thời lượng","Trạng thái","Cập nhật",""].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{items.map(item=><tr className="border-t" key={item.id}><td className="p-4"><strong>{item.name}</strong><p className="text-xs text-muted">{item.category?.name ?? "Chưa phân loại"}</p></td><td className="p-4">{money.format(item.price)}</td><td className="p-4">{item.duration} phút</td><td className="p-4"><Badge value={item.isHiddenByAdmin ? "HIDDEN_BY_ADMIN" : item.isActive ? "ACTIVE" : "INACTIVE"}/></td><td className="p-4 text-sm text-muted">{date(item.updateAt ?? item.createAt)}</td><td className="p-4"><Button variant="outline" disabled={item.isHiddenByAdmin || toggle.isPending} onClick={() => toggle.mutate(item.id,{onSuccess:()=>showToast("Đã cập nhật trạng thái dịch vụ.","success"),onError:(e)=>showToast(errorText(e),"error")})}>{item.isActive ? "Ẩn" : "Hiện"}</Button></td></tr>)}</tbody></table></div>}</div>;
}

export function ProviderServiceFormLive({serviceId}:{serviceId?:string}){const services=useProviderServicesApi();const save=useSaveProviderServiceApi();const {showToast}=useToast();const existing=services.data?.items.find(x=>x.id===serviceId);const [draft,setDraft]=useState<{name:string;description:string;price:number;duration:number;category:string}|null>(null);if(services.isLoading)return <Loading/>;if(services.isError)return <ErrorState error={services.error} retry={()=>void services.refetch()}/>;if(serviceId&&!existing)return <ErrorState error={new Error("Không tìm thấy dịch vụ trong danh sách Provider.")} retry={()=>void services.refetch()}/>;const form=draft??{name:existing?.name??"",description:existing?.description??"",price:existing?.price??0,duration:existing?.duration??30,category:existing?.category?.name??"OTHER"};const set=(patch:Partial<typeof form>)=>setDraft({...form,...patch});const invalid=!form.name.trim()||form.price<0||form.duration<=0;return <div className="space-y-5"><Header title={serviceId?"Cập nhật dịch vụ":"Tạo dịch vụ"} description="Biểu mẫu chỉ gửi các field mà Service API hiện có hỗ trợ."/><section className="mx-auto grid max-w-3xl gap-5 rounded-3xl border bg-surface p-6 sm:grid-cols-2"><Field label="Tên dịch vụ *" value={form.name} onChange={v=>set({name:v})}/><label className="text-sm font-bold">Danh mục<select className="mt-2 h-11 w-full rounded-xl border bg-surface px-3" value={form.category} onChange={e=>set({category:e.target.value})}>{["GROOMING","SPA","BOARDING","TRAINING","VETERINARY","OTHER"].map(x=><option key={x}>{x}</option>)}</select></label><Field label="Giá (VND) *" type="number" value={String(form.price)} onChange={v=>set({price:Number(v)})}/><Field label="Thời lượng (phút) *" type="number" value={String(form.duration)} onChange={v=>set({duration:Number(v)})}/><label className="text-sm font-bold sm:col-span-2">Mô tả<textarea className="mt-2 min-h-32 w-full rounded-xl border bg-surface p-3 font-normal" value={form.description} onChange={e=>set({description:e.target.value})}/></label><div className="sm:col-span-2 flex gap-3"><Button disabled={invalid||save.isPending} onClick={()=>save.mutate({id:serviceId,payload:{name:form.name.trim(),description:form.description.trim(),price:form.price,duration:form.duration,category:form.category}},{onSuccess:()=>showToast(serviceId?"Đã cập nhật dịch vụ.":"Đã tạo dịch vụ.","success"),onError:e=>showToast(errorText(e),"error")})}>{save.isPending?"Đang lưu...":"Lưu dịch vụ"}</Button><Link className="rounded-xl border px-5 py-3 text-sm font-bold" href="/provider/services">Quay lại</Link></div></section></div>}

export function ProviderBookingsLive() {
  const [status,setStatus]=useState(""); const query=useProviderBookingsApi({page:1,pageSize:50,status:status||undefined}); const action=useProviderBookingActionApi(); const {showToast}=useToast();
  if(query.isLoading)return <Loading/>; if(query.isError)return <ErrorState error={query.error} retry={()=>void query.refetch()}/>;
  const act=(id:string,type:"confirm"|"reject"|"cancel"|"no-arrival")=>{const reason=type==="reject"||type==="cancel"?window.prompt("Nhập lý do:")??undefined:undefined;if((type==="reject"||type==="cancel")&&!reason)return;action.mutate({id,action:type,reason},{onSuccess:()=>showToast("Đã cập nhật booking.","success"),onError:e=>showToast(errorText(e),"error")});};
  const items=query.data?.items??[];
  return <div className="space-y-5"><Header title="Booking" description="Danh sách và lifecycle action đang dùng API Provider thật."/><select className="h-11 rounded-xl border bg-surface px-4" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option>{["PENDING","CONFIRMED","CHECKED_IN","CHECKED_OUT","COMPLETED","CANCELLED","REJECTED","NO_ARRIVAL"].map(x=><option key={x}>{x}</option>)}</select>{items.length===0?<Empty text="Không có booking phù hợp."/>:<div className="grid gap-3">{items.map(item=><article className="rounded-3xl border bg-surface p-5" key={item.id}><div className="flex flex-col justify-between gap-4 md:flex-row"><div><div className="flex items-center gap-2"><strong>#{item.id.slice(-8)}</strong><Badge value={item.status}/></div><p className="mt-2 text-sm">{item.customer?.users?.fullName??"Khách hàng"} · {item.pet?.name??"Thú cưng"}</p><p className="text-sm text-muted">{item.service?.name??"Dịch vụ"} · {date(item.appointmentStart)}</p><p className="mt-1 font-extrabold">{money.format(item.totalAmount)}</p></div><div className="flex flex-wrap items-start gap-2">{item.status==="PENDING"&&<><Button disabled={action.isPending} onClick={()=>act(item.id,"confirm")}>Xác nhận</Button><Button variant="outline" onClick={()=>act(item.id,"reject")}>Từ chối</Button></>}{item.status==="CONFIRMED"&&<><Link className="rounded-xl bg-brand px-4 py-2 text-sm font-bold text-white" href={`/provider/bookings/${item.id}/check-in`}>Check-in QR</Link><Button variant="outline" onClick={()=>act(item.id,"no-arrival")}>Không đến</Button><Button variant="outline" onClick={()=>act(item.id,"cancel")}>Hủy</Button></>}</div></div></article>)}</div>}</div>;
}

export function ProviderWalletLive() { const query=useProviderWalletApi(); if(query.isLoading)return <Loading/>;if(query.isError)return <ErrorState error={query.error} retry={()=>void query.refetch()}/>;const w=query.data!;return <div className="space-y-5"><Header title="Ví Provider" description="Số dư được đọc trực tiếp từ wallet API."/><div className="grid gap-4 sm:grid-cols-3"><Metric label="Số dư ví" value={money.format(w.walletBalance)}/><Metric label="Số dư ký quỹ" value={money.format(w.depositBalance)}/><Metric label="Trạng thái ký quỹ" value={w.depositStatus}/></div><div className="flex flex-wrap gap-3"><LinkButton href="/provider/wallet/transactions" text="Xem giao dịch"/><LinkButton href="/provider/wallet/withdrawals" text="Yêu cầu rút tiền"/></div></div>; }
export function ProviderTransactionsLive(){const [page,setPage]=useState(1);const query=useProviderTransactionsApi({page,pageSize:20});if(query.isLoading)return <Loading/>;if(query.isError)return <ErrorState error={query.error} retry={()=>void query.refetch()}/>;const result=query.data!;return <div className="space-y-5"><Header title="Lịch sử giao dịch" description="Sổ giao dịch chỉ đọc từ Wallet API."/>{result.items.length===0?<Empty text="Chưa có giao dịch."/>:<div className="grid gap-3">{result.items.map(x=><article className="rounded-2xl border bg-surface p-4" key={x.id}><div className="flex justify-between gap-4"><div><Badge value={x.type}/><p className="mt-2 text-sm text-muted">{x.note??x.referenceId??x.id}</p><p className="text-xs text-muted">{date(x.createAt)}</p></div><strong className={x.amount>=0?"text-emerald-700":"text-red-700"}>{money.format(x.amount)}</strong></div></article>)}</div>}<Pager page={page} total={result.pagination.totalPages} setPage={setPage}/></div>}
export function ProviderWithdrawalsLive(){const [page,setPage]=useState(1);const query=useProviderWithdrawalsApi({page,pageSize:20});if(query.isLoading)return <Loading/>;if(query.isError)return <ErrorState error={query.error} retry={()=>void query.refetch()}/>;const result=query.data!;return <div className="space-y-5"><Header title="Yêu cầu rút tiền" description="Trạng thái yêu cầu được lấy từ API, không mô phỏng duyệt/chi tiền."/><div className="flex justify-end"><LinkButton href="/provider/wallet/withdrawals/create" text="Tạo yêu cầu"/></div>{result.items.length===0?<Empty text="Chưa có yêu cầu rút tiền."/>:<div className="grid gap-3">{result.items.map(x=><article className="rounded-2xl border bg-surface p-4" key={x.id}><div className="flex justify-between gap-4"><div><Badge value={x.status}/><p className="mt-2 text-sm font-bold">{x.bankCode} · {x.bankAccountNumber}</p><p className="text-xs text-muted">{date(x.requestedAt)}</p></div><strong>{money.format(x.amount)}</strong></div></article>)}</div>}<Pager page={page} total={result.pagination.totalPages} setPage={setPage}/></div>}
export function CreateWithdrawalLive(){const wallet=useProviderWalletApi();const create=useCreateWithdrawalApi();const [amount,setAmount]=useState(100000);const [reason,setReason]=useState("");const {showToast}=useToast();if(wallet.isLoading)return <Loading/>;if(wallet.isError)return <ErrorState error={wallet.error} retry={()=>void wallet.refetch()}/>;const invalid=amount<100000||amount>wallet.data!.walletBalance;return <div className="space-y-5"><Header title="Tạo yêu cầu rút tiền" description="Yêu cầu sẽ được gửi tới withdrawal API hiện có; backend kiểm tra trạng thái Provider, số dư và tài khoản ngân hàng."/><section className="mx-auto max-w-xl space-y-5 rounded-3xl border bg-surface p-6"><Metric label="Số dư ví" value={money.format(wallet.data!.walletBalance)}/><label className="block text-sm font-bold">Số tiền<Input className="mt-2" type="number" min={100000} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label>{invalid&&<p className="text-sm font-bold text-red-700">Tối thiểu 100.000₫ và không vượt quá số dư ví.</p>}<label className="block text-sm font-bold">Ghi chú<Input className="mt-2" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Không bắt buộc"/></label><Button disabled={invalid||create.isPending} onClick={()=>create.mutate({amount,reason:reason.trim()||undefined},{onSuccess:()=>showToast("Đã tạo yêu cầu rút tiền.","success"),onError:e=>showToast(errorText(e),"error")})}>{create.isPending?"Đang gửi...":"Gửi yêu cầu"}</Button></section></div>}

export function ProviderAvailabilityLive(){const query=useProviderAvailabilityApi();const save=useSaveWorkingHoursApi();const {showToast}=useToast();const defaults=Array.from({length:7},(_,dayOfWeek)=>({dayOfWeek,openTime:"08:00",closeTime:"18:00",isClosed:dayOfWeek===0}));const [draft,setDraft]=useState<WorkingHourApi[]|null>(null);if(query.hours.isLoading||query.blocks.isLoading)return <Loading/>;if(query.hours.isError||query.blocks.isError)return <ErrorState error={query.hours.error??query.blocks.error} retry={()=>{void query.hours.refetch();void query.blocks.refetch()}}/>;const hours=draft??((query.hours.data?.length?query.hours.data:defaults));const update=(day:number,patch:Partial<WorkingHourApi>)=>setDraft(hours.map(x=>x.dayOfWeek===day?{...x,...patch}:x));const invalid=hours.some(x=>!x.isClosed&&x.openTime>=x.closeTime);return <div className="space-y-5"><Header title="Lịch làm việc" description="API hiện hỗ trợ một khung giờ mỗi ngày và các khoảng thời gian bị khóa."/><div className="grid gap-3">{hours.map(x=><div className="grid gap-3 rounded-2xl border bg-surface p-4 sm:grid-cols-[130px_100px_1fr_1fr] sm:items-center" key={x.dayOfWeek}><strong>{["Chủ nhật","Thứ hai","Thứ ba","Thứ tư","Thứ năm","Thứ sáu","Thứ bảy"][x.dayOfWeek]}</strong><label className="text-sm"><input type="checkbox" checked={!x.isClosed} onChange={e=>update(x.dayOfWeek,{isClosed:!e.target.checked})}/> Mở cửa</label><Input type="time" disabled={x.isClosed} value={x.openTime} onChange={e=>update(x.dayOfWeek,{openTime:e.target.value})}/><Input type="time" disabled={x.isClosed} value={x.closeTime} onChange={e=>update(x.dayOfWeek,{closeTime:e.target.value})}/></div>)}</div>{invalid&&<p className="text-sm font-bold text-red-700">Giờ mở cửa phải trước giờ đóng cửa.</p>}<Button disabled={invalid||save.isPending} onClick={()=>save.mutate(hours.map(({dayOfWeek,openTime,closeTime,isClosed})=>({dayOfWeek,openTime,closeTime,isClosed})),{onSuccess:data=>{setDraft(data);showToast("Đã lưu lịch làm việc.","success")},onError:e=>showToast(errorText(e),"error")})}>Lưu lịch</Button><section className="rounded-3xl border bg-surface p-5"><h2 className="text-lg font-extrabold">Khoảng thời gian đã khóa</h2>{query.blocks.data?.length?<div className="mt-4 grid gap-2">{query.blocks.data.map(x=><div className="rounded-xl bg-surface-muted p-3 text-sm" key={x.id}><strong>{date(x.startAt)} – {date(x.endAt)}</strong><p className="text-muted">{x.reason??"Không có lý do"}</p></div>)}</div>:<p className="mt-3 text-sm text-muted">Chưa có khoảng thời gian bị khóa.</p>}</section></div>}
export function ProviderNotificationsLive(){const [unread,setUnread]=useState(false);const query=useProviderNotificationsApi({page:1,pageSize:50,unread:unread||undefined});const action=useNotificationActionsApi();const {showToast}=useToast();if(query.isLoading)return <Loading/>;if(query.isError)return <ErrorState error={query.error} retry={()=>void query.refetch()}/>;const items=query.data?.items??[];const mark=(id:string|"all")=>action.mutate(id,{onSuccess:()=>showToast("Đã cập nhật thông báo.","success"),onError:e=>showToast(errorText(e),"error")});return <div className="space-y-5"><Header title="Thông báo" description="Thông báo Provider được tải từ Mobile Notification API."/><div className="flex gap-3"><Button variant={unread?"outline":"default"} onClick={()=>setUnread(false)}>Tất cả</Button><Button variant={unread?"default":"outline"} onClick={()=>setUnread(true)}>Chưa đọc</Button><Button variant="outline" onClick={()=>mark("all")}>Đánh dấu tất cả đã đọc</Button></div>{items.length===0?<Empty text="Không có thông báo."/>:<div className="grid gap-3">{items.map(x=><button className={`rounded-2xl border p-4 text-left ${x.isRead?"bg-surface":"bg-brand-soft"}`} key={x.id} onClick={()=>!x.isRead&&mark(x.id)}><div className="flex items-center gap-2"><Badge value={x.type}/><span className="text-xs text-muted">{date(x.createAt)}</span></div><strong className="mt-2 block">{x.title}</strong><p className="mt-1 text-sm text-muted">{x.message}</p></button>)}</div>}</div>}

export function ProviderBusinessProfileLive(){const query=useProviderProfileApi();const update=useUpdateProviderProfileApi();const {showToast}=useToast();const [draft,setDraft]=useState<Record<string,string>|null>(null);if(query.isLoading)return <Loading/>;if(query.isError)return <ErrorState error={query.error} retry={()=>void query.refetch()}/>;const p=query.data!;const form=draft??{businessName:p.businessName,description:p.description??"",phone:p.phone??"",email:p.email??"",address:p.address??"",lat:p.lat?.toString()??"",lng:p.lng?.toString()??""};const set=(key:string,value:string)=>setDraft({...form,[key]:value});const invalid=!form.businessName.trim()||!form.address.trim()||(form.email&&!/^\S+@\S+\.\S+$/.test(form.email));return <div className="space-y-5"><Header title="Hồ sơ doanh nghiệp" description="Các trường backend đang hỗ trợ được đọc và cập nhật qua /providers/me."/><section className="grid gap-5 rounded-3xl border bg-surface p-6 md:grid-cols-2"><Field label="Tên doanh nghiệp *" value={form.businessName} onChange={v=>set("businessName",v)}/><Field label="Điện thoại" value={form.phone} onChange={v=>set("phone",v)}/><Field label="Email" value={form.email} onChange={v=>set("email",v)}/><Field label="Địa chỉ *" value={form.address} onChange={v=>set("address",v)}/><Field label="Vĩ độ" value={form.lat} onChange={v=>set("lat",v)} type="number"/><Field label="Kinh độ" value={form.lng} onChange={v=>set("lng",v)} type="number"/><label className="md:col-span-2 text-sm font-bold">Mô tả<textarea className="mt-2 min-h-32 w-full rounded-xl border bg-surface p-3 font-normal" value={form.description} onChange={e=>set("description",e.target.value)}/></label>{invalid&&<p className="md:col-span-2 text-sm font-bold text-red-700">Tên, địa chỉ và email hợp lệ là bắt buộc.</p>}<Button disabled={invalid||update.isPending} onClick={()=>update.mutate({businessName:form.businessName.trim(),description:form.description.trim(),phone:form.phone.trim(),email:form.email.trim(),address:form.address.trim(),lat:form.lat?Number(form.lat):undefined,lng:form.lng?Number(form.lng):undefined},{onSuccess:data=>{setDraft(null);showToast(`Đã lưu ${data.businessName}.`,"success")},onError:e=>showToast(errorText(e),"error")})}>Lưu thay đổi</Button></section></div>}

export function ProviderVerificationLive(){const info=useMyProviderInfo();const docs=useMyProviderDocuments();const upload=useUploadProviderDocument();const {showToast}=useToast();const [type,setType]=useState("business_license");const [file,setFile]=useState<File|null>(null);if(info.isLoading||docs.isLoading)return <Loading/>;if(info.isError||docs.isError)return <ErrorState error={info.error??docs.error} retry={()=>{void info.refetch();void docs.refetch()}}/>;return <div className="space-y-5"><Header title="Xác minh Provider" description="Trạng thái và tài liệu được lấy trực tiếp từ Provider API."/><section className="rounded-3xl border bg-surface p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-muted">Trạng thái hồ sơ</p><div className="mt-2"><Badge value={info.data!.providerStatus}/></div>{info.data!.adminNote&&<p className="mt-3 text-sm text-red-700">Ghi chú Admin: {info.data!.adminNote}</p>}</div><strong>{info.data!.businessName}</strong></div></section>{info.data!.providerStatus!=="VERIFIED"&&<section className="rounded-3xl border bg-surface p-5"><h2 className="font-extrabold">Tải tài liệu xác minh</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row"><select className="h-11 rounded-xl border bg-surface px-3" value={type} onChange={e=>setType(e.target.value)}>{["business_license","id_card_front","id_card_back","tax_code","other"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><Input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]??null)}/><Button disabled={!file||upload.isPending} onClick={()=>file&&upload.mutate({documentType:type,file},{onSuccess:()=>{setFile(null);showToast("Đã tải tài liệu lên.","success")},onError:e=>showToast(errorText(e),"error")})}>Tải lên</Button></div></section>}<section className="rounded-3xl border bg-surface p-5"><h2 className="font-extrabold">Tài liệu đã gửi</h2>{docs.data?.length?<div className="mt-4 grid gap-3 sm:grid-cols-2">{docs.data.map(x=><a className="rounded-2xl border p-4 hover:border-brand" href={x.imageUrl} target="_blank" rel="noreferrer" key={x.id}><Badge value={x.status}/><strong className="mt-2 block">{x.documentType.replaceAll("_"," ")}</strong><p className="mt-1 text-xs text-muted">{date(x.createAt)}</p>{x.adminNote&&<p className="mt-2 text-sm text-red-700">{x.adminNote}</p>}</a>)}</div>:<p className="mt-3 text-sm text-muted">Chưa có tài liệu.</p>}</section></div>}

function Empty({text}:{text:string}){return <div className="rounded-3xl border border-dashed bg-surface p-12 text-center text-sm text-muted">{text}</div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-3xl border bg-surface p-5"><p className="text-sm text-muted">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>}
function LinkButton({href,text}:{href:string;text:string}){return <Link className="rounded-xl bg-brand px-5 py-3 text-sm font-bold text-white" href={href}>{text}</Link>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="text-sm font-bold">{label}<Input className="mt-2" type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Pager({page,total,setPage}:{page:number;total:number;setPage:(p:number)=>void}){if(total<=1)return null;return <div className="flex justify-center gap-3"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>Trước</Button><span className="py-2 text-sm">{page}/{total}</span><Button variant="outline" disabled={page>=total} onClick={()=>setPage(page+1)}>Sau</Button></div>}
