"use client";

import { useEffect, useMemo, useState } from "react";
import { CustomSelect } from "@/components/ui/custom-select";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { getMockProviderRevenue, providerRevenueServices } from "@/mocks/provider/provider-revenue.mock";
import type { ProviderRevenueBookingMock, ProviderRevenueSettlementMock, ProviderRevenueTrendPoint } from "@/types/provider-revenue";

const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 });
type Range = "today" | "7days" | "month" | "custom";
const MOCK_TODAY = "2026-07-21";

export function ProviderRevenueDashboardMock() {
  const [bookings, setBookings] = useState<ProviderRevenueBookingMock[]>([]); const [settlements, setSettlements] = useState<ProviderRevenueSettlementMock[]>([]); const [loading, setLoading] = useState(true); const [range, setRange] = useState<Range>("month"); const [from, setFrom] = useState("2026-07-01"); const [to, setTo] = useState(MOCK_TODAY); const [service, setService] = useState("all"); const [payment, setPayment] = useState("all");
  useEffect(() => { let active = true; getMockProviderRevenue().then((data) => { if (active) { setBookings(data.bookings); setSettlements(data.settlements); } }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const dates = rangeDates(range, from, to); const filtered = useMemo(() => bookings.filter((item) => item.completedAt.slice(0, 10) >= dates.from && item.completedAt.slice(0, 10) <= dates.to && (service === "all" || item.service === service) && (payment === "all" || item.paymentMethod === payment)), [bookings, dates.from, dates.to, service, payment]);
  const metrics = useMemo(() => { const gross = sum(filtered, "grossAmount"); const commission = sum(filtered, "commission"); const net = sum(filtered, "netAmount"); const pending = sum(filtered.filter((item) => item.settlementStatus === "pending"), "netAmount"); const completed = sum(filtered.filter((item) => item.settlementStatus === "completed"), "netAmount"); const cash = sum(filtered.filter((item) => item.paymentMethod === "cash"), "grossAmount"); return { gross, commission, net, pending, completed, cash, online: gross - cash, withdrawn: settlements.filter((item) => item.status === "completed").reduce((total, item) => total + item.netAmount, 0) }; }, [filtered, settlements]);
  const trend = useMemo(() => buildTrend(filtered), [filtered]);
  if (loading) return <div className="space-y-5 animate-pulse"><div className="h-28 rounded-3xl bg-surface-muted" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 8 }).map((_, i) => <div key={i} className="h-28 rounded-3xl bg-surface-muted" />)}</div><div className="h-96 rounded-3xl bg-surface-muted" /></div>;
  return <div className="space-y-5"><header className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6"><h1 className="text-3xl font-black">Revenue Analytics</h1><p className="mt-2 text-sm text-muted">Explore mock booking revenue, commission, settlements, and payment mix.</p></header><RevenueFilters range={range} setRange={setRange} from={from} setFrom={setFrom} to={to} setTo={setTo} service={service} setService={setService} payment={payment} setPayment={setPayment} /><SummaryCards metrics={metrics} /><div className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,.7fr)]"><RevenueTrendChart points={trend} /><PaymentBreakdown bookings={filtered} /></div><div className="grid gap-5 xl:grid-cols-2"><RevenueByService bookings={filtered} /><RecentCompletedBookings bookings={filtered} /></div><SettlementTable settlements={settlements} /></div>;
}

function RevenueFilters(props: { range: Range; setRange: (v: Range) => void; from: string; setFrom: (v: string) => void; to: string; setTo: (v: string) => void; service: string; setService: (v: string) => void; payment: string; setPayment: (v: string) => void }) { return <section className="grid gap-3 rounded-3xl border border-border-subtle bg-surface p-4 shadow-sm md:grid-cols-2 xl:grid-cols-[180px_180px_180px_220px_190px]"><CustomSelect value={props.range} options={[{ label: "Today", value: "today" }, { label: "Last 7 days", value: "7days" }, { label: "Current month", value: "month" }, { label: "Custom range", value: "custom" }]} onValueChange={(value) => props.setRange(value as Range)} />{props.range === "custom" ? <><Input aria-label="Revenue date from" type="date" value={props.from} onChange={(e) => props.setFrom(e.target.value)} /><Input aria-label="Revenue date to" type="date" value={props.to} onChange={(e) => props.setTo(e.target.value)} /></> : <div className="col-span-2 flex items-center rounded-xl border border-border-subtle px-4 text-sm font-semibold text-muted">{rangeLabel(props.range)}</div>}<CustomSelect value={props.service} options={[{ label: "All services", value: "all" }, ...providerRevenueServices.map((item) => ({ label: item, value: item }))]} onValueChange={props.setService} /><CustomSelect value={props.payment} options={[{ label: "All payment methods", value: "all" }, ...["cash", "card", "bank_transfer", "wallet"].map((item) => ({ label: item.replaceAll("_", " "), value: item }))]} onValueChange={props.setPayment} /></section>; }
function SummaryCards({ metrics }: { metrics: Record<string, number> }) { const items = [{ key: "gross", label: "Gross revenue", tone: "text-emerald-700" }, { key: "commission", label: "Platform commission", tone: "text-red-700" }, { key: "net", label: "Provider net revenue", tone: "text-brand" }, { key: "pending", label: "Pending settlement", tone: "text-amber-700" }, { key: "completed", label: "Completed settlement", tone: "text-indigo-700" }, { key: "cash", label: "Cash revenue", tone: "text-orange-700" }, { key: "online", label: "Online revenue", tone: "text-blue-700" }, { key: "withdrawn", label: "Total withdrawn", tone: "text-purple-700" }]; return <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map((item) => <article key={item.key} className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm"><p className="text-xs font-extrabold uppercase tracking-wide text-subtle">{item.label}</p><p className={cn("mt-2 text-2xl font-black", item.tone)}>{money.format(metrics[item.key])}</p></article>)}</section>; }

function RevenueTrendChart({ points }: { points: ProviderRevenueTrendPoint[] }) { const width = 760; const height = 260; const max = Math.max(...points.map((item) => item.gross), 1); const coordinates = points.map((item, index) => `${points.length === 1 ? width / 2 : index * (width / (points.length - 1))},${height - item.gross / max * (height - 35)}`).join(" "); return <section className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6"><h2 className="text-lg font-extrabold">Revenue trend</h2><p className="mt-1 text-sm text-muted">Daily gross revenue for the selected filters.</p>{points.length ? <div className="mt-6 overflow-x-auto"><svg viewBox={`0 0 ${width} ${height + 35}`} className="min-w-[620px] w-full" role="img" aria-label="Revenue trend line chart"><defs><linearGradient id="revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#16a36a" stopOpacity=".3"/><stop offset="1" stopColor="#16a36a" stopOpacity="0"/></linearGradient></defs>{[0, .25, .5, .75, 1].map((ratio) => <line key={ratio} x1="0" x2={width} y1={height * ratio} y2={height * ratio} stroke="currentColor" className="text-border-subtle" strokeDasharray="4 5" />)}<polygon points={`0,${height} ${coordinates} ${width},${height}`} fill="url(#revenue-fill)"/><polyline points={coordinates} fill="none" stroke="#16a36a" strokeWidth="4" strokeLinejoin="round" strokeLinecap="round"/>{points.map((item, index) => { const x = points.length === 1 ? width / 2 : index * (width / (points.length - 1)); const y = height - item.gross / max * (height - 35); return <g key={item.date}><circle cx={x} cy={y} r="5" fill="#fff" stroke="#16a36a" strokeWidth="3"><title>{item.date}: {money.format(item.gross)}</title></circle>{(index === 0 || index === points.length - 1 || index % Math.ceil(points.length / 6) === 0) && <text x={x} y={height + 25} textAnchor="middle" fontSize="11" fill="currentColor">{item.date.slice(5)}</text>}</g>; })}</svg></div> : <Empty text="No revenue points match the selected filters." />}</section>; }

function RevenueByService({ bookings }: { bookings: ProviderRevenueBookingMock[] }) { const rows = providerRevenueServices.map((service) => ({ service, value: sum(bookings.filter((item) => item.service === service), "grossAmount") })).filter((item) => item.value > 0).sort((a, b) => b.value - a.value); const max = Math.max(...rows.map((item) => item.value), 1); return <section className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6"><h2 className="text-lg font-extrabold">Revenue by service</h2><div className="mt-5 space-y-4">{rows.map((row) => <div key={row.service}><div className="flex justify-between gap-3 text-sm"><span className="font-bold">{row.service}</span><span className="font-extrabold">{money.format(row.value)}</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-surface-muted"><div className="h-full rounded-full bg-brand" style={{ width: `${row.value / max * 100}%` }} /></div></div>)}{!rows.length && <Empty text="No service revenue for this period." />}</div></section>; }
function PaymentBreakdown({ bookings }: { bookings: ProviderRevenueBookingMock[] }) { const methods = ["cash", "card", "bank_transfer", "wallet"] as const; const values = methods.map((method) => ({ method, value: sum(bookings.filter((item) => item.paymentMethod === method), "grossAmount") })); const total = values.reduce((sumValue, item) => sumValue + item.value, 0); const percentages = values.map((item) => total ? item.value / total * 100 : 0); const colors = ["#f59e0b", "#3b82f6", "#8b5cf6", "#10b981"]; let cursor = 0; const gradient = percentages.map((value, index) => { const start = cursor; cursor += value; return `${colors[index]} ${start}% ${cursor}%`; }).join(", "); return <section className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6"><h2 className="text-lg font-extrabold">Payment method breakdown</h2><div className="mt-6 flex flex-col items-center gap-6 sm:flex-row"><div className="grid h-40 w-40 shrink-0 place-items-center rounded-full" style={{ background: total ? `conic-gradient(${gradient})` : "var(--color-surface-muted)" }}><div className="grid h-24 w-24 place-items-center rounded-full bg-surface text-center"><span><strong className="block text-lg">{bookings.length}</strong><span className="text-xs text-muted">bookings</span></span></div></div><div className="w-full space-y-3">{values.map((item, index) => <div key={item.method} className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2 font-bold capitalize"><i className="h-3 w-3 rounded-full" style={{ backgroundColor: colors[index] }} />{item.method.replaceAll("_", " ")}</span><span className="font-extrabold">{percentages[index].toFixed(0)}%</span></div>)}</div></div></section>; }
function RecentCompletedBookings({ bookings }: { bookings: ProviderRevenueBookingMock[] }) { const rows = [...bookings].sort((a, b) => b.completedAt.localeCompare(a.completedAt)).slice(0, 6); return <section className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6"><h2 className="text-lg font-extrabold">Recent completed bookings</h2>{rows.length ? <div className="mt-4 divide-y divide-border-subtle">{rows.map((item) => <div key={item.id} className="flex justify-between gap-3 py-3"><div><p className="text-sm font-extrabold text-brand">{item.code}</p><p className="mt-1 text-xs text-muted">{item.service} · {formatDate(item.completedAt)}</p></div><div className="text-right"><p className="text-sm font-black">{money.format(item.netAmount)}</p><p className="mt-1 text-xs capitalize text-muted">{item.paymentMethod.replaceAll("_", " ")}</p></div></div>)}</div> : <Empty text="No completed bookings match the filters." />}</section>; }
function SettlementTable({ settlements }: { settlements: ProviderRevenueSettlementMock[] }) { return <section className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6"><h2 className="text-lg font-extrabold">Settlements</h2><div className="mt-5 overflow-x-auto"><table className="min-w-[850px] w-full text-left"><thead className="text-xs font-extrabold uppercase text-subtle"><tr>{["Reference", "Period", "Gross", "Commission", "Net", "Status", "Expected / completed"].map((item) => <th key={item} className="border-b border-border-subtle px-3 py-3">{item}</th>)}</tr></thead><tbody className="divide-y divide-border-subtle">{settlements.map((item) => <tr key={item.id}><td className="px-3 py-4 font-extrabold text-brand">{item.reference}</td><td className="px-3 py-4 text-sm">{item.period}</td><td className="px-3 py-4 text-sm font-bold">{money.format(item.grossAmount)}</td><td className="px-3 py-4 text-sm text-red-700">−{money.format(item.commission)}</td><td className="px-3 py-4 text-sm font-black">{money.format(item.netAmount)}</td><td className="px-3 py-4"><span className={cn("rounded-full px-2.5 py-1 text-xs font-extrabold capitalize", item.status === "completed" ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800")}>{item.status}</span></td><td className="px-3 py-4 text-xs text-muted">{formatDate(item.completedAt ?? item.expectedAt)}</td></tr>)}</tbody></table></div></section>; }

function buildTrend(bookings: ProviderRevenueBookingMock[]): ProviderRevenueTrendPoint[] { const grouped = new Map<string, ProviderRevenueTrendPoint>(); bookings.forEach((item) => { const date = item.completedAt.slice(0, 10); const current = grouped.get(date) ?? { date, gross: 0, net: 0 }; current.gross += item.grossAmount; current.net += item.netAmount; grouped.set(date, current); }); return Array.from(grouped.values()).sort((a, b) => a.date.localeCompare(b.date)); }
function sum(items: ProviderRevenueBookingMock[], key: "grossAmount" | "commission" | "netAmount") { return items.reduce((total, item) => total + item[key], 0); }
function rangeDates(range: Range, from: string, to: string) { if (range === "today") return { from: MOCK_TODAY, to: MOCK_TODAY }; if (range === "7days") return { from: "2026-07-15", to: MOCK_TODAY }; if (range === "month") return { from: "2026-07-01", to: MOCK_TODAY }; return { from, to }; }
function rangeLabel(range: Range) { return range === "today" ? "21 Jul 2026" : range === "7days" ? "15–21 Jul 2026" : "1–21 Jul 2026"; }
function Empty({ text }: { text: string }) { return <div className="mt-5 rounded-2xl border border-dashed border-border-muted py-8 text-center text-sm font-semibold text-muted">{text}</div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
