"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { CustomSelect } from "@/components/ui/custom-select";
import { useConfirmDialog, useToast } from "@/components/ui/feedback-provider";
import { cn } from "@/lib/utils";
import type { ProviderNotificationMock, ProviderNotificationType } from "@/types/provider-notification";
import { useProviderNotificationMock } from "./notification-context";

const typeOptions: Array<{ value: ProviderNotificationType; label: string; icon: string; tone: string }> = [
  { value: "verification_update", label: "Verification update", icon: "✓", tone: "bg-emerald-100 text-emerald-800" }, { value: "new_booking", label: "New booking", icon: "+", tone: "bg-blue-100 text-blue-800" },
  { value: "booking_cancelled", label: "Booking cancelled", icon: "×", tone: "bg-red-100 text-red-800" }, { value: "upcoming_booking", label: "Upcoming booking", icon: "◷", tone: "bg-cyan-100 text-cyan-800" },
  { value: "new_message", label: "New message", icon: "✉", tone: "bg-indigo-100 text-indigo-800" }, { value: "dispute_update", label: "Dispute update", icon: "!", tone: "bg-orange-100 text-orange-800" },
  { value: "withdrawal_update", label: "Withdrawal update", icon: "↗", tone: "bg-purple-100 text-purple-800" }, { value: "low_balance", label: "Low balance", icon: "₫", tone: "bg-amber-100 text-amber-800" },
  { value: "service_moderation", label: "Service moderation", icon: "◇", tone: "bg-slate-200 text-slate-800" },
];

export function ProviderNotificationCenterMock() {
  const { notifications, unreadCount, markRead, markAllRead, remove } = useProviderNotificationMock(); const [tab, setTab] = useState<"all" | "unread">("all"); const [type, setType] = useState("all"); const [loading, setLoading] = useState(true); const router = useRouter(); const confirm = useConfirmDialog(); const { showToast } = useToast();
  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 450); return () => window.clearTimeout(timer); }, []);
  const filtered = useMemo(() => notifications.filter((item) => (tab === "all" || !item.read) && (type === "all" || item.type === type)), [notifications, tab, type]);
  function open(item: ProviderNotificationMock) { markRead(item.id); router.push(item.route); }
  async function deleteItem(item: ProviderNotificationMock) { const result = await confirm({ title: "Delete this notification?", description: "It will be removed only from the current frontend mock list.", confirmLabel: "Delete", tone: "danger" }); if (!result.confirmed) return; remove(item.id); showToast("Notification deleted locally.", "success"); }
  if (loading) return <div className="space-y-4 animate-pulse"><div className="h-28 rounded-3xl bg-surface-muted" /><div className="h-16 rounded-3xl bg-surface-muted" />{Array.from({ length: 6 }).map((_, i) => <div key={i} className="h-28 rounded-2xl bg-surface-muted" />)}</div>;
  return <div className="space-y-5"><header className="flex flex-col justify-between gap-4 rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black">Notifications</h1>{unreadCount > 0 && <span className="rounded-full bg-danger px-3 py-1 text-xs font-extrabold text-white">{unreadCount} unread</span>}</div><p className="mt-2 text-sm text-muted">Provider alerts and updates stored in frontend mock state.</p></div><Button variant="outline" disabled={unreadCount === 0} onClick={() => { markAllRead(); showToast("All notifications marked as read.", "success"); }}>Mark All as Read</Button></header><section className="flex flex-col justify-between gap-3 rounded-3xl border border-border-subtle bg-surface p-4 shadow-sm sm:flex-row"><div className="flex rounded-xl border border-border-muted p-1"><button className={cn("rounded-lg px-5 py-2 text-sm font-extrabold", tab === "all" && "bg-brand text-white")} onClick={() => setTab("all")}>All ({notifications.length})</button><button className={cn("rounded-lg px-5 py-2 text-sm font-extrabold", tab === "unread" && "bg-brand text-white")} onClick={() => setTab("unread")}>Unread ({unreadCount})</button></div><CustomSelect className="w-full sm:w-64" value={type} options={[{ label: "All notification types", value: "all" }, ...typeOptions.map((item) => ({ label: item.label, value: item.value }))]} onValueChange={setType} /></section>{filtered.length ? <section className="overflow-hidden rounded-3xl border border-border-subtle bg-surface shadow-sm"><div className="divide-y divide-border-subtle">{filtered.map((item) => <NotificationItem key={item.id} item={item} onOpen={() => open(item)} onRead={() => { markRead(item.id); showToast("Notification marked as read.", "success"); }} onDelete={() => void deleteItem(item)} />)}</div></section> : <div className="rounded-3xl border border-dashed border-border-muted bg-surface py-16 text-center"><div className="text-4xl">✓</div><h2 className="mt-3 text-lg font-extrabold">No notifications here</h2><p className="mt-1 text-sm text-muted">Try another tab or notification type.</p></div>}</div>;
}

function NotificationItem({ item, onOpen, onRead, onDelete }: { item: ProviderNotificationMock; onOpen: () => void; onRead: () => void; onDelete: () => void }) { const meta = typeOptions.find((value) => value.value === item.type)!; return <article className={cn("flex gap-3 p-4 transition sm:p-5", !item.read && "bg-brand-soft/40")}><button type="button" onClick={onOpen} className="flex min-w-0 flex-1 gap-3 text-left"><span className={cn("grid h-11 w-11 shrink-0 place-items-center rounded-2xl text-lg font-black", meta.tone)}>{meta.icon}</span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><strong className="text-sm text-foreground">{item.title}</strong>{!item.read && <i className="h-2.5 w-2.5 rounded-full bg-brand" />}</span><span className="mt-1 block text-sm leading-6 text-muted">{item.message}</span><span className="mt-2 flex flex-wrap gap-2 text-xs font-semibold text-subtle"><span>{meta.label}</span><span>·</span><span>{formatRelative(item.createdAt)}</span>{item.reference && <><span>·</span><span>{item.reference}</span></>}</span></span></button><div className="flex shrink-0 flex-col gap-1 sm:flex-row">{!item.read && <Button variant="ghost" className="h-9 px-3" onClick={onRead}>Read</Button>}<Button variant="ghost" className="h-9 px-3 text-danger" onClick={onDelete}>Delete</Button></div></article>; }
function formatRelative(value: string) { const hours = Math.max(0, Math.round((new Date("2026-07-21T18:00:00+07:00").getTime() - new Date(value).getTime()) / 3600000)); if (hours < 1) return "Just now"; if (hours < 24) return `${hours}h ago`; return `${Math.floor(hours / 24)}d ago`; }
