"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { CustomSelect } from "@/components/ui/custom-select";
import { cn } from "@/lib/utils";
import { getMockProviderWallet, providerWalletStates } from "@/mocks/provider/provider-wallet.mock";
import type { ProviderDepositStatus, ProviderWalletMock } from "@/types/provider-wallet";

const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 });
const statusMeta: Record<ProviderDepositStatus, { label: string; title: string; description: string; tone: string }> = {
  active: { label: "Active", title: "Deposit account is active", description: "Your commission deposit meets the required threshold. Cash bookings are available.", tone: "border-emerald-200 bg-emerald-50 text-emerald-900" },
  not_paid: { label: "Not paid", title: "Initial deposit required", description: "Add the minimum commission deposit before accepting cash bookings.", tone: "border-red-200 bg-red-50 text-red-900" },
  low_balance: { label: "Low balance", title: "Deposit balance is running low", description: "Reserved commissions have reduced the available deposit. Add funds to restore cash booking eligibility.", tone: "border-amber-200 bg-amber-50 text-amber-900" },
  restricted: { label: "Restricted", title: "Wallet operations are restricted", description: "Debt or a compliance hold is preventing withdrawals and cash booking acceptance.", tone: "border-purple-200 bg-purple-50 text-purple-900" },
};

export function ProviderWalletOverviewMock() {
  const [wallet, setWallet] = useState<ProviderWalletMock | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; getMockProviderWallet().then((data) => { if (active) setWallet(data); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  function selectState(status: string) { setWallet(structuredClone(providerWalletStates[status as ProviderDepositStatus])); }
  if (loading) return <div className="space-y-5 animate-pulse"><div className="h-28 rounded-3xl bg-surface-muted" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, i) => <div key={i} className="h-32 rounded-3xl bg-surface-muted" />)}</div><div className="h-80 rounded-3xl bg-surface-muted" /></div>;
  if (!wallet) return <div className="rounded-3xl border border-red-200 bg-red-50 p-8 text-center"><h1 className="text-xl font-extrabold text-red-950">Wallet unavailable</h1><p className="mt-2 text-sm text-red-800">The local mock wallet could not be loaded.</p></div>;
  const meta = statusMeta[wallet.status];
  return <div className="space-y-5"><header className="flex flex-col justify-between gap-4 rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6 lg:flex-row lg:items-center"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black text-foreground">Provider Wallet</h1><span className={cn("rounded-full border px-3 py-1 text-xs font-extrabold", meta.tone)}>{meta.label}</span></div><p className="mt-2 text-sm text-muted">Review balances, deposit health, transactions, and settlements in frontend mock mode.</p></div><div className="w-full rounded-2xl border border-dashed border-border-muted p-3 sm:w-60"><p className="mb-2 text-xs font-extrabold uppercase text-subtle">Mock wallet state</p><CustomSelect value={wallet.status} options={Object.entries(statusMeta).map(([value, item]) => ({ value, label: item.label }))} onValueChange={selectState} /></div></header><BalanceCards wallet={wallet} /><section className={cn("rounded-3xl border p-5 shadow-sm sm:p-6", meta.tone)}><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-xs font-extrabold uppercase tracking-wide">Deposit status</p><h2 className="mt-1 text-xl font-black">{meta.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 opacity-90">{meta.description}</p>{wallet.status !== "active" && <p className="mt-2 text-sm font-bold">Required minimum: {money.format(wallet.minimumDeposit)}</p>}</div>{wallet.status !== "active" && <Link href="/provider/wallet/deposit" className="inline-flex h-11 shrink-0 items-center justify-center rounded-xl bg-brand px-5 text-sm font-bold text-white">Add Funds</Link>}</div></section><div className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.7fr)]"><div className="space-y-5"><RecentTransactions wallet={wallet} /><PendingSettlements wallet={wallet} /></div><div className="space-y-5"><CashEligibility wallet={wallet} /><QuickActions /></div></div></div>;
}

function BalanceCards({ wallet }: { wallet: ProviderWalletMock }) { const items = [{ label: "Available balance", value: wallet.availableBalance, hint: "Cleared wallet funds", tone: "text-emerald-700" }, { label: "Pending balance", value: wallet.pendingBalance, hint: "Awaiting settlement", tone: "text-blue-700" }, { label: "Reserved commission", value: wallet.reservedCommission, hint: "Held for cash bookings", tone: "text-amber-700" }, { label: "Deposit balance", value: wallet.depositBalance, hint: "Commission security", tone: "text-indigo-700" }, { label: "Debt balance", value: wallet.debtBalance, hint: "Outstanding obligations", tone: wallet.debtBalance ? "text-red-700" : "text-slate-700" }, { label: "Withdrawable balance", value: wallet.withdrawableBalance, hint: "Available to withdraw", tone: "text-brand" }]; return <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.label} className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm"><p className="text-xs font-extrabold uppercase tracking-wide text-subtle">{item.label}</p><p className={cn("mt-2 text-2xl font-black", item.tone)}>{money.format(item.value)}</p><p className="mt-2 text-xs font-semibold text-muted">{item.hint}</p></article>)}</section>; }

function CashEligibility({ wallet }: { wallet: ProviderWalletMock }) { return <section className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm"><div className={cn("grid h-12 w-12 place-items-center rounded-full text-2xl", wallet.cashBookingEligible ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700")}>{wallet.cashBookingEligible ? "✓" : "×"}</div><h2 className="mt-4 text-lg font-extrabold">Cash booking eligibility</h2><p className={cn("mt-2 text-sm font-bold", wallet.cashBookingEligible ? "text-emerald-700" : "text-red-700")}>{wallet.cashBookingEligible ? "Eligible to accept cash bookings" : "Cash bookings temporarily unavailable"}</p><p className="mt-2 text-sm leading-6 text-muted">{wallet.cashBookingEligible ? "The deposit can cover estimated commissions for new cash appointments." : "Restore the required deposit and clear restrictions before accepting new cash appointments."}</p></section>; }

function RecentTransactions({ wallet }: { wallet: ProviderWalletMock }) { return <section className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-extrabold">Recent transactions</h2><p className="mt-1 text-sm text-muted">Latest local ledger activity.</p></div><Link href="/provider/wallet?view=transactions" className="text-sm font-extrabold text-brand">View all</Link></div>{wallet.transactions.length ? <div className="mt-5 divide-y divide-border-subtle">{wallet.transactions.map((item) => <div key={item.id} className="grid gap-2 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-extrabold">{item.description}</p><span className={cn("rounded-full px-2 py-0.5 text-[10px] font-extrabold capitalize", item.status === "completed" ? "bg-emerald-100 text-emerald-800" : item.status === "pending" ? "bg-amber-100 text-amber-800" : "bg-red-100 text-red-800")}>{item.status}</span></div><p className="mt-1 text-xs text-muted">{item.reference} · {formatDate(item.occurredAt)}</p></div><p className={cn("font-black", item.direction === "credit" ? "text-emerald-700" : "text-red-700")}>{item.direction === "credit" ? "+" : "−"}{money.format(item.amount)}</p></div>)}</div> : <Empty text="No wallet transactions for this mock state." />}</section>; }

function PendingSettlements({ wallet }: { wallet: ProviderWalletMock }) { return <section className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6"><h2 className="text-lg font-extrabold">Pending settlements</h2><p className="mt-1 text-sm text-muted">Booking revenue waiting for dispute windows or processing.</p>{wallet.pendingSettlements.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{wallet.pendingSettlements.map((item) => <article key={item.id} className="rounded-2xl bg-surface-muted p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-extrabold uppercase text-brand">{item.bookingCode}</p><p className="mt-1 text-sm font-extrabold">{item.serviceName}</p></div><span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-extrabold capitalize text-amber-800">{item.status.replaceAll("_", " ")}</span></div><dl className="mt-4 space-y-2 text-sm"><Row label="Gross" value={money.format(item.grossAmount)} /><Row label="Commission" value={`−${money.format(item.commission)}`} /><Row label="Net settlement" value={money.format(item.netAmount)} strong /></dl><p className="mt-3 text-xs font-semibold text-muted">Expected {formatDate(item.expectedAt)}</p></article>)}</div> : <Empty text="No pending settlements for this wallet state." />}</section>; }

function QuickActions() { const actions = [{ label: "Add Funds", description: "Top up commission deposit", href: "/provider/wallet/deposit", icon: "+" }, { label: "Withdraw", description: "Request a payout", href: "/provider/withdrawals", icon: "↗" }, { label: "View Transactions", description: "Review wallet activity", href: "/provider/wallet?view=transactions", icon: "≡" }, { label: "View Revenue", description: "Open revenue analytics", href: "/provider/revenue", icon: "⌁" }]; return <section className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm"><h2 className="text-lg font-extrabold">Quick actions</h2><div className="mt-4 grid gap-2">{actions.map((action) => <Link key={action.label} href={action.href} className="flex items-center gap-3 rounded-2xl border border-border-subtle p-3 transition hover:border-brand hover:bg-brand-soft"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-soft text-xl font-black text-brand">{action.icon}</span><span><strong className="block text-sm">{action.label}</strong><span className="text-xs text-muted">{action.description}</span></span></Link>)}</div></section>; }
function Empty({ text }: { text: string }) { return <div className="mt-5 rounded-2xl border border-dashed border-border-muted py-10 text-center text-sm font-semibold text-muted">{text}</div>; }
function Row({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <div className="flex justify-between gap-3"><dt className={strong ? "font-extrabold" : "text-muted"}>{label}</dt><dd className={strong ? "font-black text-brand" : "font-bold"}>{value}</dd></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
