"use client";

import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { CustomSelect } from "@/components/ui/custom-select";
import { Input } from "@/components/ui/input";
import { useConfirmDialog, useToast } from "@/components/ui/feedback-provider";
import { cn } from "@/lib/utils";
import { getMockProviderAvailability, providerAvailabilityMock } from "@/mocks/provider/provider-availability.mock";
import type { AvailabilityException, AvailabilitySettings, AvailabilityTimeRange, CalendarSlot, WeeklyDaySchedule } from "@/types/provider-availability";

const weekdays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const tones = { available: "bg-emerald-100 text-emerald-800 border-emerald-200", blocked: "bg-slate-200 text-slate-700 border-slate-300", booked: "bg-blue-100 text-blue-800 border-blue-200", holiday: "bg-red-100 text-red-800 border-red-200" };

export function TimeRangeEditor({ range, onChange, onRemove }: { range: AvailabilityTimeRange; onChange: (range: AvailabilityTimeRange) => void; onRemove: () => void }) {
  return <div className="flex items-center gap-2"><Input aria-label="Start time" type="time" value={range.start} onChange={(e) => onChange({ ...range, start: e.target.value })} /><span className="text-sm font-bold text-subtle">to</span><Input aria-label="End time" type="time" value={range.end} onChange={(e) => onChange({ ...range, end: e.target.value })} /><button type="button" aria-label="Remove time range" onClick={onRemove} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl text-lg font-black text-danger hover:bg-red-50">×</button></div>;
}

export function DayScheduleRow({ value, error, onChange }: { value: WeeklyDaySchedule; error?: string; onChange: (value: WeeklyDaySchedule) => void }) {
  return <div className="rounded-2xl border border-border-subtle bg-surface-muted p-3"><div className="grid gap-3 lg:grid-cols-[110px_100px_1fr_auto] lg:items-start"><strong className="pt-2 text-sm">{value.day}</strong><button type="button" onClick={() => onChange({ ...value, isOpen: !value.isOpen })} className={cn("mt-1 rounded-full px-3 py-1.5 text-xs font-extrabold", value.isOpen ? "bg-emerald-100 text-emerald-800" : "bg-slate-200 text-slate-700")}>{value.isOpen ? "Open" : "Closed"}</button><div className="space-y-2">{value.isOpen ? value.ranges.map((range) => <TimeRangeEditor key={range.id} range={range} onChange={(next) => onChange({ ...value, ranges: value.ranges.map((item) => item.id === range.id ? next : item) })} onRemove={() => onChange({ ...value, ranges: value.ranges.filter((item) => item.id !== range.id) })} />) : <p className="py-2 text-sm text-muted">Not accepting bookings</p>}{value.isOpen && !value.ranges.length && <p className="py-2 text-sm font-semibold text-amber-800">Add at least one working range.</p>}</div>{value.isOpen && <Button variant="outline" className="h-10 px-3" onClick={() => onChange({ ...value, ranges: [...value.ranges, { id: crypto.randomUUID(), start: "09:00", end: "12:00" }] })}>+ Range</Button>}</div>{error && <p className="mt-2 text-xs font-bold text-danger">{error}</p>}</div>;
}

export function WeeklyScheduleEditor({ value, errors, onChange, onCopy }: { value: WeeklyDaySchedule[]; errors: Record<string, string>; onChange: (value: WeeklyDaySchedule[]) => void; onCopy: () => void }) {
  return <section className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-extrabold">Weekly schedule</h2><p className="mt-1 text-sm text-muted">Configure multiple operating ranges per day.</p></div><Button variant="outline" onClick={onCopy}>Copy Monday to weekdays</Button></div><div className="mt-5 space-y-3">{value.map((day) => <DayScheduleRow key={day.day} value={day} error={errors[day.day]} onChange={(next) => onChange(value.map((item) => item.day === next.day ? next : item))} />)}</div></section>;
}

export function CapacitySettingsCard({ capacity, duration, error, onChange }: { capacity: number; duration: number; error?: string; onChange: (capacity: number, duration: number) => void }) {
  return <section className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm"><h2 className="text-lg font-extrabold">Capacity settings</h2><p className="mt-1 text-sm text-muted">Defaults for generated slots.</p><div className="mt-5 space-y-4"><label className="block"><span className="mb-2 block text-sm font-bold">Maximum capacity</span><Input type="number" min={1} value={capacity} onChange={(e) => onChange(Number(e.target.value), duration)} /></label><label className="block"><span className="mb-2 block text-sm font-bold">Default slot duration</span><CustomSelect value={String(duration)} options={[30, 45, 60, 90, 120].map((item) => ({ label: `${item} minutes`, value: String(item) }))} onValueChange={(item) => onChange(capacity, Number(item))} /></label>{error && <p className="text-xs font-bold text-danger">{error}</p>}</div></section>;
}

type DialogProps = { bookings: AvailabilitySettings["bookings"]; onClose: () => void; onSubmit: (value: AvailabilityException) => void };
export function BlockTimeDialog({ bookings, onClose, onSubmit }: DialogProps) {
  const [date, setDate] = useState("2026-07-18"); const [start, setStart] = useState("13:00"); const [end, setEnd] = useState("15:00"); const [error, setError] = useState("");
  function submit() { const today = new Date(); today.setHours(0, 0, 0, 0); if (new Date(`${date}T00:00:00`) < today) return setError("Past dates cannot be blocked."); if (start >= end) return setError("Start time must be earlier than end time."); if (bookings.some((item) => item.date === date && overlaps(start, end, item.start, item.end))) return setError("A confirmed booking occupies this time and cannot be removed."); onSubmit({ id: crypto.randomUUID(), date, type: "blocked_time", title: "Provider blocked time", ranges: [{ id: crypto.randomUUID(), start, end }] }); }
  return <Modal title="Block a time range" onClose={onClose}><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Date</span><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label><label><span className="mb-2 block text-sm font-bold">Start</span><Input type="time" value={start} onChange={(e) => setStart(e.target.value)} /></label><label><span className="mb-2 block text-sm font-bold">End</span><Input type="time" value={end} onChange={(e) => setEnd(e.target.value)} /></label></div>{error && <p className="mt-3 text-sm font-bold text-danger">{error}</p>}<div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={submit}>Block time</Button></div></Modal>;
}

export function ScheduleExceptionDialog({ bookings, onClose, onSubmit }: DialogProps) {
  const [date, setDate] = useState("2026-07-25"); const [type, setType] = useState<"holiday" | "special_hours">("holiday"); const [title, setTitle] = useState("Special schedule"); const [start, setStart] = useState("09:00"); const [end, setEnd] = useState("14:00"); const [error, setError] = useState("");
  function submit() { if (!title.trim()) return setError("Add a reason."); if (type === "special_hours" && start >= end) return setError("Start time must be earlier than end time."); if (type === "holiday" && bookings.some((item) => item.date === date)) return setError("A confirmed booking prevents closing this date."); onSubmit({ id: crypto.randomUUID(), date, type, title, ranges: type === "holiday" ? [] : [{ id: crypto.randomUUID(), start, end }] }); }
  return <Modal title="Create schedule exception" onClose={onClose}><div className="space-y-4"><label className="block"><span className="mb-2 block text-sm font-bold">Type</span><CustomSelect value={type} options={[{ label: "Holiday / closed", value: "holiday" }, { label: "Special working hours", value: "special_hours" }]} onValueChange={(item) => setType(item as typeof type)} /></label><label className="block"><span className="mb-2 block text-sm font-bold">Date</span><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label><label className="block"><span className="mb-2 block text-sm font-bold">Reason</span><Input value={title} onChange={(e) => setTitle(e.target.value)} /></label>{type === "special_hours" && <div className="grid grid-cols-2 gap-3"><Input type="time" value={start} onChange={(e) => setStart(e.target.value)} /><Input type="time" value={end} onChange={(e) => setEnd(e.target.value)} /></div>}</div>{error && <p className="mt-3 text-sm font-bold text-danger">{error}</p>}<div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={submit}>Create exception</Button></div></Modal>;
}

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[60] grid place-items-center bg-black/50 p-4 backdrop-blur-sm" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div role="dialog" aria-modal="true" className="w-full max-w-lg rounded-3xl bg-surface p-6 shadow-2xl"><div className="flex justify-between gap-3"><h2 className="text-xl font-extrabold">{title}</h2><Button variant="ghost" className="h-9 px-3" onClick={onClose}>Close</Button></div><div className="mt-5">{children}</div></div></div>; }

export function AvailabilityCalendar({ settings, onBlock, onException, onUnblock }: { settings: AvailabilitySettings; onBlock: () => void; onException: () => void; onUnblock: (item: AvailabilityException) => void }) {
  const [view, setView] = useState<"month" | "week">("month"); const [weekStart, setWeekStart] = useState(13); const days = view === "month" ? Array.from({ length: 31 }, (_, i) => i + 1) : Array.from({ length: 7 }, (_, i) => weekStart + i).filter((day) => day <= 31);
  return <section className="rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><h2 className="text-lg font-extrabold">Availability calendar</h2><p className="mt-1 text-sm text-muted">July 2026 · mock calendar slots.</p></div><div className="flex flex-wrap gap-2"><div className="flex rounded-xl border border-border-muted p-1"><button className={cn("rounded-lg px-3 py-2 text-sm font-bold", view === "month" && "bg-brand text-white")} onClick={() => setView("month")}>Month</button><button className={cn("rounded-lg px-3 py-2 text-sm font-bold", view === "week" && "bg-brand text-white")} onClick={() => setView("week")}>Week</button></div><Button variant="outline" onClick={onException}>Create exception</Button><Button onClick={onBlock}>Block time</Button></div></div><div className="mt-4 flex flex-wrap gap-2">{Object.entries(tones).map(([state, tone]) => <span key={state} className={cn("rounded-full border px-2.5 py-1 text-xs font-bold capitalize", tone)}>{state}</span>)}</div>{view === "week" && <div className="mt-4 flex justify-end gap-2"><Button variant="outline" className="h-9 px-3" disabled={weekStart <= 1} onClick={() => setWeekStart((v) => Math.max(1, v - 7))}>Previous</Button><Button variant="outline" className="h-9 px-3" disabled={weekStart >= 25} onClick={() => setWeekStart((v) => Math.min(25, v + 7))}>Next</Button></div>}<div className={cn("mt-5 grid gap-2", view === "month" ? "grid-cols-7" : "grid-cols-1 md:grid-cols-7")}>{view === "month" && weekdays.map((day) => <div key={day} className="py-2 text-center text-xs font-extrabold text-subtle">{day}</div>)}{view === "month" && <><div /><div /></>}{days.map((day) => <CalendarDay key={day} day={day} settings={settings} expanded={view === "week"} onUnblock={onUnblock} />)}</div></section>;
}

function CalendarDay({ day, settings, expanded, onUnblock }: { day: number; settings: AvailabilitySettings; expanded: boolean; onUnblock: (item: AvailabilityException) => void }) { const date = `2026-07-${String(day).padStart(2, "0")}`; const exception = settings.exceptions.find((item) => item.date === date); const slots = slotsForDate(date, settings); return <div className={cn("min-h-28 rounded-2xl border border-border-subtle p-2", expanded && "min-h-72")}><div className="flex justify-between"><strong className="text-sm">{day}</strong>{exception && <button className="text-[10px] font-extrabold text-danger" onClick={() => onUnblock(exception)}>Unblock</button>}</div><div className="mt-2 space-y-1">{slots.slice(0, expanded ? 8 : 3).map((slot) => <div key={slot.id} className={cn("truncate rounded-lg border px-1.5 py-1 text-[10px] font-bold", tones[slot.state])}>{slot.start && `${slot.start} `}{slot.label}</div>)}{!slots.length && <p className="text-[10px] font-semibold text-subtle">Closed</p>}{!expanded && slots.length > 3 && <p className="text-[10px] font-bold text-subtle">+{slots.length - 3} slots</p>}</div></div>; }

export function ProviderAvailabilityMockWorkflow() {
  const [settings, setSettings] = useState<AvailabilitySettings | null>(null); const [saved, setSaved] = useState<AvailabilitySettings | null>(null); const [loading, setLoading] = useState(true); const [errors, setErrors] = useState<Record<string, string>>({}); const [dialog, setDialog] = useState<"block" | "exception" | null>(null); const { showToast } = useToast(); const confirm = useConfirmDialog();
  useEffect(() => { let active = true; getMockProviderAvailability().then((data) => { if (active) { setSettings(data); setSaved(data); } }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const dirty = useMemo(() => settings && saved ? JSON.stringify(settings) !== JSON.stringify(saved) : false, [settings, saved]);
  function validate(value: AvailabilitySettings) { const next: Record<string, string> = {}; if (value.capacity <= 0) next.capacity = "Capacity must be greater than zero."; value.weeklySchedule.forEach((day) => { if (!day.isOpen) return; if (!day.ranges.length) next[day.day] = "Open days need at least one time range."; else if (day.ranges.some((range) => range.start >= range.end)) next[day.day] = "Start must be earlier than end."; else if (hasOverlap(day.ranges)) next[day.day] = "Time ranges cannot overlap."; }); setErrors(next); return !Object.keys(next).length; }
  async function save() { if (!settings || !validate(settings)) return showToast("Correct the schedule validation errors.", "error"); const result = await confirm({ title: "Save availability changes?", description: "This only updates the current frontend mock session.", confirmLabel: "Save changes", tone: "success" }); if (!result.confirmed) return; setSaved(structuredClone(settings)); showToast("Availability saved in mock mode.", "success"); }
  async function reset() { const result = await confirm({ title: "Reset unsaved changes?", confirmLabel: "Reset", tone: "danger" }); if (!result.confirmed) return; setSettings(structuredClone(saved ?? providerAvailabilityMock)); setErrors({}); showToast("Unsaved changes reset.", "info"); }
  if (loading) return <div className="space-y-5 animate-pulse"><div className="h-28 rounded-3xl bg-surface-muted" /><div className="grid gap-5 xl:grid-cols-[1fr_300px]"><div className="h-[600px] rounded-3xl bg-surface-muted" /><div className="h-72 rounded-3xl bg-surface-muted" /></div><div className="h-96 rounded-3xl bg-surface-muted" /></div>;
  if (!settings) return <div className="rounded-3xl border border-red-200 bg-red-50 p-8 text-center"><h1 className="text-xl font-extrabold text-red-950">Availability unavailable</h1></div>;
  const currentSettings = settings;
  function addException(item: AvailabilityException) { setSettings({ ...currentSettings, exceptions: [...currentSettings.exceptions.filter((old) => !(old.date === item.date && old.type === item.type)), item] }); setDialog(null); showToast("Calendar exception added locally.", "success"); }
  async function unblock(item: AvailabilityException) { if (currentSettings.bookings.some((booking) => booking.date === item.date && item.ranges.some((range) => overlaps(range.start, range.end, booking.start, booking.end)))) return showToast("A confirmed booking prevents removing this slot.", "error"); const result = await confirm({ title: "Remove this exception?", description: item.title, confirmLabel: "Unblock date" }); if (!result.confirmed) return; setSettings({ ...currentSettings, exceptions: currentSettings.exceptions.filter((old) => old.id !== item.id) }); }
  return <div className="space-y-5"><header className="flex flex-col justify-between gap-4 rounded-3xl border border-border-subtle bg-surface p-5 shadow-sm sm:p-6 lg:flex-row lg:items-center"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black">Availability</h1>{dirty && <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-extrabold text-amber-800">Unsaved changes</span>}</div><p className="mt-2 text-sm text-muted">Configure weekly hours, capacity, and one-off exceptions in mock mode.</p></div><div className="flex gap-2"><Button variant="outline" disabled={!dirty} onClick={() => void reset()}>Reset Changes</Button><Button onClick={() => void save()}>Save Changes</Button></div></header><div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><WeeklyScheduleEditor value={settings.weeklySchedule} errors={errors} onChange={(weeklySchedule) => setSettings({ ...settings, weeklySchedule })} onCopy={() => { const monday = settings.weeklySchedule[0]; setSettings({ ...settings, weeklySchedule: settings.weeklySchedule.map((day, index) => index < 5 ? { ...day, isOpen: monday.isOpen, ranges: monday.ranges.map((range) => ({ ...range, id: crypto.randomUUID() })) } : day) }); showToast("Monday copied to weekdays.", "success"); }} /><CapacitySettingsCard capacity={settings.capacity} duration={settings.defaultSlotDuration} error={errors.capacity} onChange={(capacity, defaultSlotDuration) => setSettings({ ...settings, capacity, defaultSlotDuration })} /></div><AvailabilityCalendar settings={settings} onBlock={() => setDialog("block")} onException={() => setDialog("exception")} onUnblock={(item) => void unblock(item)} />{dialog === "block" && <BlockTimeDialog bookings={settings.bookings} onClose={() => setDialog(null)} onSubmit={addException} />}{dialog === "exception" && <ScheduleExceptionDialog bookings={settings.bookings} onClose={() => setDialog(null)} onSubmit={addException} />}</div>;
}

function overlaps(aStart: string, aEnd: string, bStart: string, bEnd: string) { return aStart < bEnd && aEnd > bStart; }
function hasOverlap(ranges: AvailabilityTimeRange[]) { const sorted = [...ranges].sort((a, b) => a.start.localeCompare(b.start)); return sorted.some((range, index) => index > 0 && range.start < sorted[index - 1].end); }
function slotsForDate(date: string, settings: AvailabilitySettings): CalendarSlot[] { const holiday = settings.exceptions.find((item) => item.date === date && item.type === "holiday"); if (holiday) return [{ id: holiday.id, date, start: "", end: "", state: "holiday", label: holiday.title }]; const blocks = settings.exceptions.filter((item) => item.date === date && item.type === "blocked_time").flatMap((item) => item.ranges.map((range) => ({ ...range, title: item.title }))); const special = settings.exceptions.find((item) => item.date === date && item.type === "special_hours"); const dayIndex = (new Date(`${date}T12:00:00`).getDay() + 6) % 7; const day = settings.weeklySchedule[dayIndex]; const ranges = special?.ranges ?? (day.isOpen ? day.ranges : []); const slots: CalendarSlot[] = []; ranges.forEach((range) => { for (let cursor = minutes(range.start); cursor + settings.defaultSlotDuration <= minutes(range.end); cursor += settings.defaultSlotDuration) { const start = time(cursor); const end = time(cursor + settings.defaultSlotDuration); const booking = settings.bookings.find((item) => item.date === date && overlaps(start, end, item.start, item.end)); const block = blocks.find((item) => overlaps(start, end, item.start, item.end)); slots.push({ id: `${date}-${start}`, date, start, end, state: booking ? "booked" : block ? "blocked" : "available", label: booking ? booking.customerName : block ? block.title : `${settings.capacity} spots`, bookingId: booking?.id }); } }); return slots; }
function minutes(value: string) { const [hour, minute] = value.split(":").map(Number); return hour * 60 + minute; }
function time(value: number) { return `${String(Math.floor(value / 60)).padStart(2, "0")}:${String(value % 60).padStart(2, "0")}`; }
