"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { useConfirmDialog } from "@/components/ui/feedback-provider";
import { adminBookingsMock, getMockAdminBookings } from "@/mocks/admin/admin-bookings.mock";
import type { AdminBookingMock } from "@/types/admin";
const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 });
export function AdminBookingListMock() { const [items, setItems] = useState<AdminBookingMock[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { let active = true; getMockAdminBookings().then((data) => { if (active) setItems(data); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []); if (loading) return <div className="h-96 animate-pulse rounded-3xl bg-surface-muted" />; return <div className="space-y-5"><Header title="Booking Monitoring" description="Read-only mock oversight across customers, providers, payments, and disputes." /><div className="overflow-x-auto rounded-3xl border border-border-subtle bg-surface"><table className="min-w-[1300px] w-full text-left"><thead className="bg-surface-muted text-xs font-extrabold uppercase text-subtle"><tr>{["Booking", "Customer", "Provider", "Service", "Appointment", "Status", "Payment", "Dispute", "Amount", ""].map((x) => <th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-border-subtle">{items.map((b) => <tr key={b.id}><td className="px-4 py-4"><Link href={`/admin/bookings/${b.id}`} className="font-extrabold text-brand">{b.code}</Link></td><td className="px-4 py-4 text-sm">{b.customer}</td><td className="px-4 py-4 text-sm">{b.provider}</td><td className="px-4 py-4 text-sm font-bold">{b.service}</td><td className="px-4 py-4 text-xs">{date(b.appointmentAt)}</td><td className="px-4 py-4 text-sm capitalize">{b.status.replaceAll("_", " ")}</td><td className="px-4 py-4 text-xs capitalize">{b.paymentMethod}<br />{b.paymentStatus.replaceAll("_", " ")}</td><td className="px-4 py-4">{b.disputeFlag ? <span className="text-sm font-bold text-red-700">Flagged</span> : "—"}</td><td className="px-4 py-4 font-black">{money.format(b.amount)}</td><td className="px-4 py-4"><Link className="text-sm font-bold text-brand" href={`/admin/bookings/${b.id}`}>Inspect →</Link></td></tr>)}</tbody></table></div></div>; }
export function AdminBookingDetailMock({ id }: { id: string }) { const booking = adminFallback(id); const confirm = useConfirmDialog(); async function preview() { await confirm({ title: "Preview admin intervention", description: "This dialog demonstrates a possible admin workflow. No booking status, payment, wallet, or dispute transaction will change.", confirmLabel: "Close Preview" }); } return <div className="space-y-5"><Header title={booking.code} description={`${booking.customer} · ${booking.provider}`} /><div className="flex justify-end"><Button variant="outline" onClick={() => void preview()}>Preview Intervention</Button></div><div className="grid gap-5 xl:grid-cols-2"><Section title="Booking snapshot"><Grid items={{ Customer: booking.customer, Provider: booking.provider, Pet: booking.pet, Service: booking.service, Appointment: date(booking.appointmentAt), Status: booking.status }} /></Section><Section title="Payment & commission"><Grid items={{ Method: booking.paymentMethod, "Payment status": booking.paymentStatus, Amount: money.format(booking.amount), Commission: money.format(booking.commission), "Provider net": money.format(booking.amount - booking.commission) }} /></Section><Section title="Complete timeline"><List items={booking.timeline.map((x) => `${x.event} · ${x.actor} · ${date(x.occurredAt)}`)} /></Section><Section title="Mock wallet transactions"><List items={booking.walletTransactions.map((x) => `${x.type} · ${money.format(x.amount)} · ${x.status}`)} /></Section><Section title="Mock QR logs"><List items={booking.qrLogs.map((x) => `${x.event} · ${x.result} · ${date(x.occurredAt)}`)} /></Section><Section title="Dispute">{booking.dispute ? <Grid items={{ Code: booking.dispute.code, Reason: booking.dispute.reason, Status: booking.dispute.status }} /> : <p className="text-sm text-muted">No related dispute.</p>}</Section><Section title="Audit events"><List items={booking.auditEvents.map((x) => `${x.action} · ${x.actor} · ${date(x.occurredAt)}`)} /></Section></div></div>; }
function adminFallback(id: string) { const exact = adminBookingsMock.find((item) => item.id === id); const index = Number(id.match(/\d+/)?.[0] ?? 1) - 1; return exact ?? adminBookingsMock[Math.max(0, index) % adminBookingsMock.length]; }
function Header({ title, description }: { title: string; description: string }) { return <header className="rounded-3xl border border-border-subtle bg-surface p-6"><h1 className="text-3xl font-black">{title}</h1><p className="mt-2 text-sm text-muted">{description}</p></header>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-border-subtle bg-surface p-5"><h2 className="text-lg font-extrabold">{title}</h2><div className="mt-4">{children}</div></section>; }
function Grid({ items }: { items: Record<string, string> }) { return <dl className="grid gap-3 sm:grid-cols-2">{Object.entries(items).map(([k,v]) => <div key={k} className="rounded-2xl bg-surface-muted p-3"><dt className="text-xs font-extrabold uppercase text-subtle">{k}</dt><dd className="mt-1 text-sm font-bold capitalize">{v.replaceAll("_", " ")}</dd></div>)}</dl>; }
function List({ items }: { items: string[] }) { return <div className="space-y-2">{items.map((x,i) => <p key={i} className="rounded-xl bg-surface-muted p-3 text-sm">{x}</p>)}</div>; }
function date(v:string){return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));}
